In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pymongo

In [2]:
client = pymongo.MongoClient('mongodb+srv://keerthivasan:apple123@cluster0.cz79j69.mongodb.net/')

db = client.sample_airbnb
collection = db.listingsAndReviews

In [3]:
data = []
for i in collection.find():
    data.append(i)

In [4]:
data[0]

{'_id': '1003530',
 'listing_url': 'https://www.airbnb.com/rooms/1003530',
 'name': 'New York City - Upper West Side Apt',
 'summary': '',
 'space': 'Murphy bed, optional second bedroom available. Wifi available, Hulu, Netflix, TV Eat-in kitchen. Bathroom with great shower/bath.  Washer/dryer in basement.',
 'description': "Murphy bed, optional second bedroom available. Wifi available, Hulu, Netflix, TV Eat-in kitchen. Bathroom with great shower/bath.  Washer/dryer in basement. New York City! Great neighborhood - many terrific restaurants, bakeries, bagelries. Within easy walking distance are restaurants with the cuisines from India, Thailand, Japan, China, Mexico, South America and Europe.  As well as the many small independent stores that line Broadway, there chain stores such as Urban Outfitters (clothing), Whole Foods (groceries), Sephora (cosmetics), Michaels (crafts), and Modell's (sporting goods). Equidistant to Central Park and Riverside Park which have walking/running/biking trails as well as tennis and racquet ball courts. 10-15 blocks from Columbia University between Broadway and Amsterdam. The International Hostel across the street is an airport shuttle bus and double-decker tour bus stop.  The Hostel also has services available to the neighborhood such as lectures, brochures, etc. Convenientl",
 'neighborhood_overview': "Great neighborhood - many terrific restaurants, bakeries, bagelries. Within easy walking distance are restaurants with the cuisines from India, Thailand, Japan, China, Mexico, South America and Europe.  As well as the many small independent stores that line Broadway, there chain stores such as Urban Outfitters (clothing), Whole Foods (groceries), Sephora (cosmetics), Michaels (crafts), and Modell's (sporting goods). Equidistant to Central Park and Riverside Park which have walking/running/biking trails as well as tennis and racquet ball courts. 10-15 blocks from Columbia University between Broadway and Amsterdam. The International Hostel across the street is an airport shuttle bus and double-decker tour bus stop.  The Hostel also has services available to the neighborhood such as lectures, brochures, etc.",
 'notes': 'My cat, Samantha, are in and out during the summer.  The apt is layed out in such a  way that each bedroom is very private.',
 'transit': 'Conveniently located near 1, 2, 3, B & C subway lines. Also buses on Columbus Avenue (downtown), Amsterdam Avenue (uptown), and Broadway (uptown/downtown). Also near origination/termination of M60 bus which goes to/from LaGuardia Airport.',
 'access': 'New York City!',
 'interaction': '',
 'house_rules': 'No smoking is permitted in the apartment. All towels that are used should be placed in the bath tub upon departure. I have a cat, Samantha, who can stay or go, whichever is preferred.   Please text me upon departure.',
 'property_type': 'Apartment',
 'room_type': 'Private room',
 'bed_type': 'Real Bed',
 'minimum_nights': '12',
 'maximum_nights': '360',
 'cancellation_policy': 'strict_14_with_grace_period',
 'last_scraped': datetime.datetime(2019, 3, 7, 5, 0),
 'calendar_last_scraped': datetime.datetime(2019, 3, 7, 5, 0),
 'first_review': datetime.datetime(2013, 4, 29, 4, 0),
 'last_review': datetime.datetime(2018, 8, 12, 4, 0),
 'accommodates': 2,
 'bedrooms': 1,
 'beds': 1,
 'number_of_reviews': 70,
 'bathrooms': Decimal128('1.0'),
 'amenities': ['Internet',
  'Wifi',
  'Air conditioning',
  'Kitchen',
  'Elevator',
  'Buzzer/wireless intercom',
  'Heating',
  'Family/kid friendly',
  'Washer',
  'Dryer',
  'translation missing: en.hosting_amenity_50'],
 'price': Decimal128('135.00'),
 'security_deposit': Decimal128('0.00'),
 'cleaning_fee': Decimal128('135.00'),
 'extra_people': Decimal128('0.00'),
 'guests_included': Decimal128('1'),
 'images': {'thumbnail_url': '',
  'medium_url': '',
  'picture_url': 'https://a0.muscache.com/im/pictures/15074036/a97119ed_original.jpg?aki_policy=large',
  'xl_picture_url': ''},
 'host': {'host_id': '454250',
  'host_url': 'https://www.airbnb.com/users/show/454250',
  'host_name': 'Greta',
  'host_location': 'New York, New York, United States',
  'host_about': 'By now I have lived longer in the city than the country however I feel equally at home in each. I like to keep one foot in each and help others to do the same!',
  'host_response_time': 'within an hour',
  'host_thumbnail_url': 'https://a0.muscache.com/im/pictures/f1022be4-e72a-4b35-b6d2-3d2736ddaff9.jpg?aki_policy=profile_small',
  'host_picture_url': 'https://a0.muscache.com/im/pictures/f1022be4-e72a-4b35-b6d2-3d2736ddaff9.jpg?aki_policy=profile_x_medium',
  'host_neighbourhood': '',
  'host_response_rate': 100,
  'host_is_superhost': True,
  'host_has_profile_pic': True,
  'host_identity_verified': True,
  'host_listings_count': 3,
  'host_total_listings_count': 3,
  'host_verifications': ['email',
   'phone',
   'reviews',
   'jumio',
   'offline_government_id',
   'government_id']},
 'address': {'street': 'New York, NY, United States',
  'suburb': 'Manhattan',
  'government_area': 'Upper West Side',
  'market': 'New York',
  'country': 'United States',
  'country_code': 'US',
  'location': {'type': 'Point',
   'coordinates': [-73.96523, 40.79962],
   'is_location_exact': False}},
 'availability': {'availability_30': 0,
  'availability_60': 0,
  'availability_90': 0,
  'availability_365': 93},
 'review_scores': {'review_scores_accuracy': 10,
  'review_scores_cleanliness': 9,
  'review_scores_checkin': 10,
  'review_scores_communication': 10,
  'review_scores_location': 10,
  'review_scores_value': 10,
  'review_scores_rating': 94},
 'reviews': [{'_id': '4351675',
   'date': datetime.datetime(2013, 4, 29, 4, 0),
   'listing_id': '1003530',
   'reviewer_id': '3708459',
   'reviewer_name': 'Josh',
   'comments': "i had a really pleasant stay at greta's place. the location is super convenient -- and the area is fun, with lots of hidden gems. the apartment was comfortable and charming. greta was accommodating and hospitable and left some great cupcakes in the fridge. i give this place a strong endorsement."},
  {'_id': '4848277',
   'date': datetime.datetime(2013, 5, 28, 4, 0),
   'listing_id': '1003530',
   'reviewer_id': '4609491',
   'reviewer_name': 'Ralf',
   'comments': 'Greta has been a great host, and her apartment a great place to stay. Perfectly located for our adventures around NYC, it is a place full of character and, as I see it, a very authentic NY Apartment that makes you feel at home imediately. Great neighbourhood, great infrastructure around the apartment block. Very good for a perfect stay.'},
  {'_id': '5094175',
   'date': datetime.datetime(2013, 6, 11, 4, 0),
   'listing_id': '1003530',
   'reviewer_id': '6741662',
   'reviewer_name': 'Mame',
   'comments': "Greta was wonderful. We arrived late at night and she made sure we were able to get in. We also had to transfer to a hotel for work, and she allowed us to keep our belongings there until 3 so we wouldn't be carting our luggage until we needed to. The apartment was clean and large and in a wonderful neighborhood. She had lists and menus of places to eat. I couldn't have been happier with our arrangement. Thanks Greta!"},
  {'_id': '5497796',
   'date': datetime.datetime(2013, 7, 2, 4, 0),
   'listing_id': '1003530',
   'reviewer_id': '474156',
   'reviewer_name': 'Lars',
   'comments': "Greta's place is very well located, so close to the MTA 1 line, which takes you up and down Manhattan, which was perfect for me.  It was an easy 3 minute walk and be on your way to anywhere in NY. \r\nThe shower is something else, the best water pressure I have experienced in a long time.\r\nI thought the decor was cool and eclectic, Greta must have an artistic streak. The Murphy bed was comfortable, and the AC unit (not pictured) kept it nice and cool.  \r\nAlthough I didn't meet her, she arranged for a neighbor to meet me and show me in. He was cool and so were any other neighbors that I met. \r\nShe also left a list of suggestions where to shop and eat, along with menus which was helpful when I needed a late night meal. \r\nHighly recommended. \r\n"},
  {'_id': '6933005',
   'date': datetime.datetime(2013, 8, 31, 4, 0),
   'listing_id': '1003530',
   'reviewer_id': '6067127',
   'reviewer_name': 'Nicole',
   'comments': "I had a wonderful stay at Greta's NYC apartment. The apartment was clean and comfortable. She was a wonderful and informative host. I felt very welcomed in her home."},
  {'_id': '7205029',
   'date': datetime.datetime(2013, 9, 10, 4, 0),
   'listing_id': '1003530',
   'reviewer_id': '7743438',
   'reviewer_name': 'Ute',
   'comments': 'Hi Greta,\r\nyou have a wonderful place. We had a great time an felt really comfortable - little bit like beeing home in NY :)\r\nEverything worked out pretty good, also the connection to La Guardia Airport was perfect.\r\n\r\nThanks again :)\r\n'},
  {'_id': '7464858',
   'date': datetime.datetime(2013, 9, 21, 4, 0),
   'listing_id': '1003530',
   'reviewer_id': '8543724',
   'reviewer_name': 'Drew',
   'comments': 'Greta was very welcoming and helpful. Prompt email communication.\r\n\r\nA great stay for those in town to see Broadway shows, shopping or sight seeing the West Side. A few minutes walking and I was in Central Park.\r\n\r\nA definite recommendation.'},
  {'_id': '7515354',
   'date': datetime.datetime(2013, 9, 23, 4, 0),
   'listing_id': '1003530',
   'reviewer_id': '1683177',
   'reviewer_name': 'Don',
   'comments': 'Greta was flexible about our sign-in time, helpful as we arrived, and kind to return to us a bag that we left in her apartment.  The apartment is wonderfully located for transportation and things to do.  It is compact and comfy, full of interesting books and prints.  The bed is quite firm.'},
  {'_id': '7871931',
   'date': datetime.datetime(2013, 10, 7, 4, 0),
   'listing_id': '1003530',
   'reviewer_id': '2871729',
   'reviewer_name': 'Heidi',
   'comments': 'We spent three nights in Greta’s apartment. Her kitchen is fully-equipped and the sleeping arrangements are extremely comfortable. Greta is a very accommodating host and easy to communicate with. She was very gracious about our later-than-expected arrival and allowed us to stay in her apartment on our departure day until we left for an early evening flight. Her apartment is very well-located, with food markets, drug stores, restaurants and coffee shops within a block of her building. The building is ½ block from the #1 subway line, enabling easy access to all parts of Manhattan.'},
  {'_id': '8136769',
   'date': datetime.datetime(2013, 10, 17, 4, 0),
   'listing_id': '1003530',
   'reviewer_id': '7811780',
   'reviewer_name': 'Julia',
   'comments': "We enjoyed our stay in Greta's apartment very much. The location is perfect, near Central Park, Broadway and everything, and the apartment is extremely cosy. Greta was very welcoming and helpful. We had a great time and felt really comfortable. Thanks :-)\r\n"},
  {'_id': '8210485',
   'date': datetime.datetime(2013, 10, 21, 4, 0),
   'listing_id': '1003530',
   'reviewer_id': '8119019',
   'reviewer_name': 'Diane',
   'comments': "Our stay are Greta's was wonderful- she was so accomodating and welcoming.  Her apartment is lovely and such a great place to unwind from the hurried family weekend weekend we had.  Greta even accomodated the joining of my niece and nephew for one of the two nights with no problem.. Thank you so much, Greta, for your hospitality!  "},
  {'_id': '8478870',
   'date': datetime.datetime(2013, 11, 2, 4, 0),
   'listing_id': '1003530',
   'reviewer_id': '8140760',
   'reviewer_name': 'Linda',
   'comments': 'Greta was a gracious and accommodating host, even coming over during our stay to reset the wifi connections.  The location of the apartment is ideal, basically half a short block to the subway.  Her list of neighborhood restaurants was very helpful and we sampled as many as we were able to. She has everything organized well.'},
  {'_id': '8587648',
   'date': datetime.datetime(2013, 11, 6, 5, 0),
   'listing_id': '1003530',
   'reviewer_id': '9307997',
   'reviewer_name': 'Maureen',
   'comments': "Greta's apartment was comfortable and clean and the neighborhood was easily accessible to museums and other locations. A bit noisy at night."},
  {'_id': '8768655',
   'date': datetime.datetime(2013, 11, 17, 5, 0),
   'listing_id': '1003530',
   'reviewer_id': '9464736',
   'reviewer_name': 'George',
   'comments': 'Greta was extremely helpful throughout this process!  Communication was maintained throughout the process and throughout our stay.  She was able to answer any questions we had and even gave suggestions for us.  Her instructions were awesome and the information left at her apartment were great!  There was even a binder with additional information like places to eat and places to go.  She even took the time to make sure we knew how to use the radiator!  Being from Hawaii, we had no knowledge about radiators and how to use them - we really appreciated her thoughtfulness!'},
  {'_id': '9179262',
   'date': datetime.datetime(2013, 12, 11, 5, 0),
   'listing_id': '1003530',
   'reviewer_id': '9405167',
   'reviewer_name': 'Whitney',
   'comments': "Greta's apartment was homey, clean and just the right size for two (probably even three) people. Greta was extremely helpful in getting us settled and providing information about the neighborhood....etc. Murphy bed was very firm but comfortable. Great water pressure in shower. Apt is close to everything and  the neighborhood has so much to offer. I would definitely recommend Greta's place.  "},
  {'_id': '9428838',
   'date': datetime.datetime(2013, 12, 28, 5, 0),
   'listing_id': '1003530',
   'reviewer_id': '10297643',
   'reviewer_name': 'Deborah & Tim',
   'comments': "The apartment is very homey - it felt like I was staying in a friend's apartment. The bed is surprisingly comfy and firm (I have never slept in a Murphy bed before) and the shower had plenty of hot water and great pressure. Greta was very communicative and friendly, and was also incredibly accommodating when I had something come up unexpectedly and needed to stay a couple hours longer than I anticipated. Overall all it was a very cozy stay in a great location!"},
  {'_id': '9543118',
   'date': datetime.datetime(2014, 1, 2, 5, 0),
   'listing_id': '1003530',
   'reviewer_id': '8828184',
   'reviewer_name': 'Catherine',
   'comments': 'The location of this appartment was ideal! Just minutes away the subway and walking distance from Central Park, Riverside Park, and many good restaurants on Broadway. A quaint appartment, with a lot of cachet. I recommend it!!'},
  {'_id': '20872115',
   'date': datetime.datetime(2014, 10, 6, 4, 0),
   'listing_id': '1003530',
   'reviewer_id': '7838233',
   'reviewer_name': 'Brandon',
   'comments': 'What a delightful apartment!  I plan to stay here next time I bring family to New York. I would describe the apartment as a very warm, personal, comfortable and homey place to stay. It’s a corner apartment with good light, lots of books and  very good energy. Plus, the beds are quite comfortable. My daughter exclaimed “Hey Dad, come lie down in this one. You’ll never want to get up!”\r\n\r\nThe neighborhood was incredibly well located and enjoyable. The train stops  a half block away, and there are numerous excellent restaurants and conveniences close by. Greta, the host, provides a first-rate list of recommendations.\r\n\r\nGreta was a personable, helpful and extremely welcoming host. She was very quick to respond to my online inquiries and, once we arrived, to any further requests for advice.\r\n'},
  {'_id': '22257920',
   'date': datetime.datetime(2014, 11, 2, 4, 0),
   'listing_id': '1003530',
   'reviewer_id': '4034556',
   'reviewer_name': 'Aparna',
   'comments': 'Greta was a lovely host! She was communicative, helpful and flexible during the booking process and very responsive and friendly when we were at her place in NYC. The house is charming and comfortable, and very conveniently located right by the 1 train. We were two of us and only used one room, but the house can fit another person or two. \r\nFor anyone visiting NYC and looking to be in the city but not in the midst of the city noise, this is a great place to stay! You can be downtown in 20 minutes. '},
  {'_id': '23415037',
   'date': datetime.datetime(2014, 11, 30, 5, 0),
   'listing_id': '1003530',
   'reviewer_id': '22685675',
   'reviewer_name': 'Karolina',
   'comments': "I stayed at Greta's place for 3 days! It was a really pleasant stay! The bed was really comfortable. The place was clean and cozy. A minute from the subway station! I didnt meet Greta in person, but we were communicating all the time and she was really helpful and kind with everything I needed! I would love to stay again the next time! :) i surely recommend it! "},
  {'_id': '23924172',
   'date': datetime.datetime(2014, 12, 14, 5, 0),
   'listing_id': '1003530',
   'reviewer_id': '16534063',
   'reviewer_name': 'Paul',
   'comments': "Staying at Greta's apartment was delightful!  It's a wonderful, quirky New York apartment -- very compact, but also very comfy and accurately portrayed in the pictures.  The Murphy (fold-down) bed has a very thick memory foam mattress that is extremely comfortable.  Samantha (the cat) was a sweet little presence, but she kept mostly to herself so we barely saw her.  The location is great, less than a block to the 1 line, and there are several nice restaurants in the neighborhood.  Finally, Greta herself was a perfect host:  kind but not intrusive, thoughtful in her preparations for guests, and available should any problems arise (though none did).  A great airbnb experience!"},
  {'_id': '28737168',
   'date': datetime.datetime(2015, 3, 29, 4, 0),
   'listing_id': '1003530',
   'reviewer_id': '29115141',
   'reviewer_name': 'Catherine',
   'comments': 'Greta was a great host.  She met us late on Friday and explained everything about the apartment which we found very comfortable and fun.  I would highly recommend this apartment to anyone.  It is not luxurious but well-equipped and I loved the location, near Central Park and easy walk to museums.\r\n'},
  {'_id': '29274122',
   'date': datetime.datetime(2015, 4, 6, 4, 0),
   'listing_id': '1003530',
   'reviewer_id': '18417452',
   'reviewer_name': 'Paul',
   'comments': "Apt is beautifully as advertised, a comfortable place and beds, kitchen and bath. Arrival and departure were really well coordinated by host, the lovely Greta. Location is fabulously convenient on upper West side by subway, Amsterdam and Broadway restaurants, bars and history. We'd stay here again.  "},
  {'_id': '29610000',
   'date': datetime.datetime(2015, 4, 10, 4, 0),
   'listing_id': '1003530',
   'reviewer_id': '27919376',
   'reviewer_name': 'Anika',
   'comments': 'Greta was a lovely host, making sure we settled in well and could contact her easily if there were any problems. \r\nThe apartment is cosy with very comfortable beds and a well equipped kitchen in case you need a place to cook. It is also a nice neighborhood, with a lot of great places to eat nearby and it is a minute away from a subway station, so you are well connected to the rest of the city. We had a great time! '},
  {'_id': '29775810',
   'date': datetime.datetime(2015, 4, 12, 4, 0),
   'listing_id': '1003530',
   'reviewer_id': '20415509',
   'reviewer_name': 'Jane',
   'comments': 'My daughter and I stayed the weekend at Gretas place.  Greta was herself away for the weekend but everything was in great shape for us to stay and Greta was very available by phone for any questions.  Everything was very tidy and clean..comfy beds and good shower.  It was like home.  The location in the city is perfect..close to the park and subway.  I highly recommend Gretas home for aNew York stay!'},
  {'_id': '30732097',
   'date': datetime.datetime(2015, 4, 26, 4, 0),

In [5]:
pd.set_option('display.max_columns', 500)

In [6]:
airbnb = pd.DataFrame(data)
#airbnb

In [7]:
airbnb.to_csv('airbnb.csv', index=False)

In [8]:
airbnb_1 = pd.read_csv('airbnb.csv')
airbnb_1

,_id,listing_url,name,summary,space,description,neighborhood_overview,notes,transit,access,interaction,house_rules,property_type,room_type,bed_type,minimum_nights,maximum_nights,cancellation_policy,last_scraped,calendar_last_scraped,first_review,last_review,accommodates,bedrooms,beds,number_of_reviews,bathrooms,amenities,price,security_deposit,cleaning_fee,extra_people,guests_included,images,host,address,availability,review_scores,reviews,weekly_price,monthly_price,reviews_per_month
0,1003530,https://www.airbnb.com/rooms/1003530,New York City - Upper West Side Apt,NaN,"Murphy bed, optional second bedroom available....","Murphy bed, optional second bedroom available....",Great neighborhood - many terrific restaurants...,"My cat, Samantha, are in and out during the su...","Conveniently located near 1, 2, 3, B & C subwa...",New York City!,NaN,No smoking is permitted in the apartment. All ...,Apartment,Private room,Real Bed,12,360,strict_14_with_grace_period,2019-03-07 05:00:00,2019-03-07 05:00:00,2013-04-29 04:00:00,2018-08-12 04:00:00,2,1.0,1.0,70,1.0,"['Internet', 'Wifi', 'Air conditioning', 'Kitc...",135.0,0.0,135.0,0.0,1,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '454250', 'host_url': 'https://www...","{'street': 'New York, NY, United States', 'sub...","{'availability_30': 0, 'availability_60': 0, '...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '4351675', 'date': datetime.datetime(...",NaN,NaN,NaN
1,10057826,https://www.airbnb.com/rooms/10057826,Deluxe Loft Suite,Loft Suite Deluxe @ Henry Norman Hotel Located...,This loft unit features a kitchenette and is f...,Loft Suite Deluxe @ Henry Norman Hotel Located...,Greenpoint is an artsy Brooklyn neighborhood f...,NaN,NaN,"Guest will have access to common terraces, lou...",NaN,Guest must leave a copy of credit card with fr...,Apartment,Entire home/apt,Real Bed,3,1125,strict_14_with_grace_period,2019-03-07 05:00:00,2019-03-07 05:00:00,2016-01-03 05:00:00,2018-02-18 05:00:00,4,0.0,2.0,5,1.0,"['TV', 'Cable TV', 'Internet', 'Wifi', 'Air co...",205.0,NaN,NaN,0.0,1,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '47554473', 'host_url': 'https://w...","{'street': 'Brooklyn, NY, United States', 'sub...","{'availability_30': 30, 'availability_60': 31,...","{'review_scores_accuracy': 9, 'review_scores_c...","[{'_id': '58665374', 'date': datetime.datetime...",NaN,NaN,NaN
2,10051164,https://www.airbnb.com/rooms/10051164,Catete's Colonial Big Hause Room B,"Old floor, intirely reformed, destined to rece...",Este quarto está preparado para acomodar confo...,"Old floor, intirely reformed, destined to rece...","A Grande Morada situa-se no Bairro do Catete, ...",A casa possui um potencial incrível para receb...,Perto do metrô e várias linhas de ônibus. Aces...,O hóspedes poderão acessar espaços compartilha...,"Sou geógrafa, gosto de arte e cultura. Moro ne...",NaN,House,Private room,Real Bed,2,1125,strict_14_with_grace_period,2019-02-11 05:00:00,2019-02-11 05:00:00,2016-02-10 05:00:00,2016-02-10 05:00:00,8,1.0,8.0,1,4.0,"['TV', 'Cable TV', 'Internet', 'Wifi', 'Air co...",250.0,0.0,0.0,40.0,4,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '51326285', 'host_url': 'https://w...","{'street': 'Rio de Janeiro, Rio de Janeiro, Br...","{'availability_30': 10, 'availability_60': 10,...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '61992538', 'date': datetime.datetime...",NaN,NaN,NaN
3,10030955,https://www.airbnb.com/rooms/10030955,Apt Linda Vista Lagoa - Rio,Quarto com vista para a Lagoa Rodrigo de Freit...,NaN,Quarto com vista para a Lagoa Rodrigo de Freit...,NaN,NaN,NaN,NaN,NaN,NaN,Apartment,Private room,Real Bed,1,1125,flexible,2019-02-11 05:00:00,2019-02-11 05:00:00,NaN,NaN,2,1.0,1.0,0,2.0,"['TV', 'Cable TV', 'Internet', 'Wifi', 'Air co...",701.0,1000.0,250.0,0.0,1,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '51496939', 'host_url': 'https://w...","{'street': 'Rio de Janeiro, Rio de Janeiro, Br...","{'availability_30': 28, 'availability_60': 58,...",{},[],NaN,NaN,NaN
4,10059244,https://www.airbnb.com/rooms/10059244,Ligne verte - à 15 min de métro du centre ville.,À 30 secondes du métro Joliette. Belle grande ...,NaN,À 30 secondes du métro Joliette. Belle grande ...,L'appartement se trouve à 4 minutes de marche ...,NaN,"Stationnement dans la rue, à 30 secondes du mé...",Vous avez accès à tout l'appartement.,Une amie sera disponible en cas de besoin.,Non fumeur Respect des voisins Respect des bie...,Apartment,Entire home/apt,Real Bed,2,1125,moderate,2019-03-11 04:00:00,2019-03-11 04:00:00,NaN,NaN,2,0.0,1.0,0,1.0,"['TV', 'Internet', 'Wifi', 'Kitchen', 'Free pa...",43.0,NaN,NaN,12.0,1,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '7140229', 'host_url': 'https://ww...","{'street': 'Montréal, Québec, Canada', 'suburb...","{'availability_30': 0, 'availability_60': 0, '...",{},[],NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5550,9834391,https://www.airbnb.com/rooms/9834391,Lindo apto quarto e sala ao lado do mar de Copa!,"Lindo apartamento todo novinho, quarto (de cas...","Apto tem tudo o que o hóspede pode precisar, t...","Lindo apartamento todo novinho, quarto (de cas...",Staying at this apartment you will find everyt...,NaN,This apartment is located at the heart of Copa...,You will have access to the whole apartment a...,Eu como anfitriã estarei a disposição para res...,NaN,Apartment,Entire home/apt,Real Bed,2,1125,strict_14_with_grace_period,2019-02-11 05:00:00,2019-02-11 05:00:00,2017-11-04 04:00:00,2019-02-04 05:00:00,4,1.0,2.0,19,1.0,"['TV', 'Cable TV', 'Internet', 'Wifi', 'Air co...",119.0,0.0,150.0,0.0,1,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '1403065', 'host_url': 'https://ww...","{'street': 'Rio de Janeiro, Rio de Janeiro, Br...","{'availability_30': 17, 'availability_60': 35,...","{'review_scores_accuracy': 10, 'review_scores_...","[{'_id': '209162839', 'date': datetime.datetim...",NaN,NaN,NaN
5551,9867316,https://www.airbnb.com/rooms/9867316,Beautiful Place in the Middle of Manhattan,Beautiful place only a couple blocks from main...,NaN,Beautiful place only a couple blocks from main...,Central Park,NaN,NaN,NaN,NaN,1. NO smoking 2. NO outside guests 3. Please t...,Apartment,Entire home/apt,Real Bed,1,1125,strict_14_with_grace_period,2019-03-07 05:00:00,2019-03-07 05:00:00,2016-02-11 05:00:00,2019-02-16 05:00:00,2,1.0,1.0,180,1.0,"['Wifi', 'Air conditioning', 'Kitchen', 'Pets ...",160.0,250.0,40.0,20.0,2,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '40540485', 'host_url': 'https://w...","{'street': 'New York, NY, United States', 'sub...","{'availability_30': 2, 'availability_60': 11, ...","{'review_scores_accuracy': 9, 'review_scores_c...","[{'_id': '62108866', 'date': datetime.datetime...",NaN,3999.0,NaN
5552,9907907,https://www.airbnb.com/rooms/9907907,Large double room in Bondi,A bright large double room is available in a b...,NaN,A bright large double room is available in a b...,NaN,NaN,The flat is exactly half way between the shops...,"Guests will have access to the full residence,...",I will be spending the whole of the Easter per...,We like to keep the flat clean and tidy so wou...,Apartment,Private room,Real Bed,3,1125,moderate,2019-03-07 05:00:00,2019-03-07 05:00:00,NaN,NaN,2,1.0,1.0,0,1.0,"['TV', 'Internet', 'Wifi', 'Kitchen', 'Washer'...",60.0,NaN,50.0,50.0,2,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '47615848', 'host_url': 'https://w...","{'street': 'Bondi Beach, NSW, Australia', 'sub...","{'availability_30': 0, 'availability_60': 0, '...",{},[],NaN,NaN,NaN
5553,9917859,https://www.airbnb.com/rooms/9917859,StayIN Oporto Música - Apartment,Acabamos de decorar-lo para receber os primeir...,NaN,Acabamos de decorar-lo para receber os primeir...,NaN,NaN,NaN,NaN,NaN,NaN,Apartment,Entire home/apt,Real Bed,1,1125,strict_14_with_grace_period,2019-02-16 05:00:00,2019-02-16 05:00:00,2016-05-08 04:00:00,2019-01-02 05:00:00,16,8.0,8.0,20,4.0,"['TV', 'Cable TV', 'Wifi', 'Kitchen', 'Elevato...",500.0,200.0,80.0,30.0,16,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '2296185', 'host_url': 'https://ww...","{'street': 'Porto, Porto, Portugal', 'suburb':...","{'availability_30': 28, 'availability_60': 54,...","{'review_scores_accuracy': 9, 'review_scores_c...","[{'_id': '73527641', 'date': datetime.datetime...",NaN,NaN,NaN
5554,9985696,https://www.airbnb.com/rooms/9985696,Kadıköy-Altıyol,Kadıköy merkezde 2+1 dairem vardır.Çok kalabal...,NaN,Kadıköy merkezde 2+1 dairem vardır.Çok kalabal...,NaN,NaN,NaN,NaN,NaN,NaN,House,Entire home/apt,Real Bed,1,1125,flexible,2019-02-18 05:00:00,2019-02-18 05:00:00,NaN,NaN,2,2.0,3.0,0,1.0,"['TV', 'Cable TV', 'Internet', 'Wifi', 'Kitche...",501.0,NaN,NaN,0.0,1,"{'thumbnail_url': '', 'medium_url': '', 'pictu...","{'host_id': '51303748', 'host_url': 'https://w...","{'street': 'Kadıköy, İstanbul, Turkey', 'subur...","{'availability_30': 30, 'availability_60': 60,...",{},[],NaN,NaN,NaN

In [9]:
airbnb_1.drop(columns=['_id','address','host','availability','review_scores','amenities','images','reviews','listing_url',
                       'summary','first_review','last_review','interaction','cleaning_fee','space','description',
                       'neighborhood_overview','notes','transit','house_rules','access','last_scraped',
                       'calendar_last_scraped','security_deposit',],inplace=True)

In [10]:
airbnb_1.shape

(5555, 18)

In [11]:
airbnb_1.columns

Index(['name', 'property_type', 'room_type', 'bed_type', 'minimum_nights',
       'maximum_nights', 'cancellation_policy', 'accommodates', 'bedrooms',
       'beds', 'number_of_reviews', 'bathrooms', 'price', 'extra_people',
       'guests_included', 'weekly_price', 'monthly_price',
       'reviews_per_month'],
      dtype='object')

In [12]:
missing_values = airbnb_1.isnull().sum()
print(missing_values)

name                      8
property_type             0
room_type                 0
bed_type                  0
minimum_nights            0
maximum_nights            0
cancellation_policy       0
accommodates              0
bedrooms                  5
beds                     13
number_of_reviews         0
bathrooms                10
price                     0
extra_people              0
guests_included           0
weekly_price           4841
monthly_price          4899
reviews_per_month      5461
dtype: int64

In [13]:
airbnb_1.drop(columns=['weekly_price','monthly_price','reviews_per_month'], inplace=True)

In [14]:
# filling the missing values using statistical techniques
airbnb_1 = airbnb_1.fillna({'name':airbnb_1['name'].mode()[0],
                'bedrooms': airbnb_1['bedrooms'].mean(),
                'beds': airbnb_1['beds'].mean(),
                'bathrooms':airbnb_1['bathrooms'].mean()})

In [15]:
airbnb_1.isnull().sum()

name                   0
property_type          0
room_type              0
bed_type               0
minimum_nights         0
maximum_nights         0
cancellation_policy    0
accommodates           0
bedrooms               0
beds                   0
number_of_reviews      0
bathrooms              0
price                  0
extra_people           0
guests_included        0
dtype: int64

# Data Type Correction

In [16]:
airbnb_1.dtypes

name                    object
property_type           object
room_type               object
bed_type                object
minimum_nights           int64
maximum_nights           int64
cancellation_policy     object
accommodates             int64
bedrooms               float64
beds                   float64
number_of_reviews        int64
bathrooms              float64
price                  float64
extra_people           float64
guests_included          int64
dtype: object

In [17]:
# correcting data type of columns
airbnb_1['bedrooms'] = airbnb_1['bedrooms'].astype("int64")
airbnb_1['beds'] = airbnb_1['beds'].astype("int64")
airbnb_1['bathrooms'] = airbnb_1['bathrooms'].astype("int64")
airbnb_1['extra_people'] = airbnb_1['extra_people'].astype("int64")

In [18]:
airbnb_1.dtypes

name                    object
property_type           object
room_type               object
bed_type                object
minimum_nights           int64
maximum_nights           int64
cancellation_policy     object
accommodates             int64
bedrooms                 int64
beds                     int64
number_of_reviews        int64
bathrooms                int64
price                  float64
extra_people             int64
guests_included          int64
dtype: object

In [19]:
airbnb_1.shape

(5555, 15)

In [20]:
airbnb_1.drop_duplicates(inplace=True)

In [21]:
airbnb_1.duplicated().sum()

0

In [22]:
airbnb_1.describe()

,minimum_nights,maximum_nights,accommodates,bedrooms,beds,number_of_reviews,bathrooms,price,extra_people,guests_included
count,5554.000000,5.554000e+03,5554.000000,5554.000000,5554.000000,5554.000000,5554.000000,5554.000000,5554.000000,5554.000000
mean,5.565178,1.383025e+06,3.506122,1.411415,2.071480,27.611451,1.258192,278.774937,22.792942,1.747389
std,22.615814,5.257393e+07,2.297137,1.041626,1.617849,49.801481,0.683703,842.291108,69.337710,1.487482
min,1.000000,1.000000e+00,1.000000,0.000000,0.000000,0.000000,0.000000,9.000000,0.000000,1.000000
25%,1.000000,5.900000e+01,2.000000,1.000000,1.000000,1.000000,1.000000,70.000000,0.000000,1.000000
50%,2.000000,1.125000e+03,3.000000,1.000000,2.000000,5.000000,1.000000,129.000000,0.000000,1.000000
75%,3.000000,1.125000e+03,4.000000,2.000000,3.000000,32.000000,1.000000,280.000000,20.000000,2.000000
max,1250.000000,2.147484e+09,16.000000,20.000000,25.000000,533.000000,16.000000,48842.000000,2346.000000,16.000000

In [23]:
Q1 = airbnb_1['minimum_nights'].quantile(0.25)
Q3 = airbnb_1['minimum_nights'].quantile(0.75)
IQR = Q3 - Q1

# Define the lower and upper bounds for outlier detection
lower_bound = Q1 - (1.5 * IQR)
upper_bound = Q3 + (1.5 * IQR)


print(lower_bound ,upper_bound)

-2.0 6.0

In [24]:
airbnb_1.minimum_nights=airbnb_1.minimum_nights.clip(upper_bound , lower_bound )

In [25]:
Q1 = airbnb_1['maximum_nights'].quantile(0.25)
Q3 = airbnb_1['maximum_nights'].quantile(0.75)
IQR = Q3 - Q1

# Define the lower and upper bounds for outlier detection
lower_bound = Q1 - (1.5 * IQR)
upper_bound = Q3 + (1.5 * IQR)


print(lower_bound ,upper_bound)

-1540.0 2724.0

In [26]:
Q1 = airbnb_1['accommodates'].quantile(0.25)
Q3 = airbnb_1['accommodates'].quantile(0.75)
IQR = Q3 - Q1

# Define the lower and upper bounds for outlier detection
lower_bound = Q1 - (1.5 * IQR)
upper_bound = Q3 + (1.5 * IQR)


print(lower_bound ,upper_bound)

-1.0 7.0

In [27]:
airbnb_1.accommodates=airbnb_1.accommodates.clip(upper_bound , lower_bound )

In [28]:
Q1 = airbnb_1['bedrooms'].quantile(0.25)
Q3 = airbnb_1['bedrooms'].quantile(0.75)
IQR = Q3 - Q1

# Define the lower and upper bounds for outlier detection
lower_bound = Q1 - (1.5 * IQR)
upper_bound = Q3 + (1.5 * IQR)


print(lower_bound ,upper_bound)

-0.5 3.5

In [29]:
airbnb_1.accommodates=airbnb_1.accommodates.clip(upper_bound , lower_bound )

In [30]:
Q1 = airbnb_1['beds'].quantile(0.25)
Q3 = airbnb_1['beds'].quantile(0.75)
IQR = Q3 - Q1

# Define the lower and upper bounds for outlier detection
lower_bound = Q1 - (1.5 * IQR)
upper_bound = Q3 + (1.5 * IQR)


print(lower_bound ,upper_bound)

-2.0 6.0

In [31]:
airbnb_1.beds=airbnb_1.beds.clip(upper_bound , lower_bound )

In [32]:
Q1 = airbnb_1['number_of_reviews'].quantile(0.25)
Q3 = airbnb_1['number_of_reviews'].quantile(0.75)
IQR = Q3 - Q1

# Define the lower and upper bounds for outlier detection
lower_bound = Q1 - (1.5 * IQR)
upper_bound = Q3 + (1.5 * IQR)


print(lower_bound ,upper_bound)

-45.5 78.5

In [33]:
Q1 = airbnb_1['bathrooms'].quantile(0.25)
Q3 = airbnb_1['bathrooms'].quantile(0.75)
IQR = Q3 - Q1

# Define the lower and upper bounds for outlier detection
lower_bound = Q1 - (1.5 * IQR)
upper_bound = Q3 + (1.5 * IQR)


print(lower_bound ,upper_bound)

1.0 1.0

In [34]:
airbnb_1.bathrooms=airbnb_1.bathrooms.clip(upper_bound , lower_bound )

In [35]:
airbnb_1.duplicated().sum()

0

In [36]:
airbnb_1

,name,property_type,room_type,bed_type,minimum_nights,maximum_nights,cancellation_policy,accommodates,bedrooms,beds,number_of_reviews,bathrooms,price,extra_people,guests_included
0,New York City - Upper West Side Apt,Apartment,Private room,Real Bed,6.0,360,strict_14_with_grace_period,2.0,1,1.0,70,1.0,135.0,0,1
1,Deluxe Loft Suite,Apartment,Entire home/apt,Real Bed,3.0,1125,strict_14_with_grace_period,3.5,0,2.0,5,1.0,205.0,0,1
2,Catete's Colonial Big Hause Room B,House,Private room,Real Bed,2.0,1125,strict_14_with_grace_period,3.5,1,6.0,1,1.0,250.0,40,4
3,Apt Linda Vista Lagoa - Rio,Apartment,Private room,Real Bed,1.0,1125,flexible,2.0,1,1.0,0,1.0,701.0,0,1
4,Ligne verte - à 15 min de métro du centre ville.,Apartment,Entire home/apt,Real Bed,2.0,1125,moderate,2.0,0,1.0,0,1.0,43.0,12,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5550,Lindo apto quarto e sala ao lado do mar de Copa!,Apartment,Entire home/apt,Real Bed,2.0,1125,strict_14_with_grace_period,3.5,1,2.0,19,1.0,119.0,0,1
5551,Beautiful Place in the Middle of Manhattan,Apartment,Entire home/apt,Real Bed,1.0,1125,strict_14_with_grace_period,2.0,1,1.0,180,1.0,160.0,20,2
5552,Large double room in Bondi,Apartment,Private room,Real Bed,3.0,1125,moderate,2.0,1,1.0,0,1.0,60.0,50,2
5553,StayIN Oporto Música - Apartment,Apartment,Entire home/apt,Real Bed,1.0,1125,strict_14_with_grace_period,3.5,8,6.0,20,1.0,500.0,30,16
5554,Kadıköy-Altıyol,House,Entire home/apt,Real Bed,1.0,1125,flexible,2.0,2,3.0,0,1.0,501.0,0,1

In [37]:
airbnb_1.to_csv('airbnb_main.csv', index=False)

In [38]:
a = pd.DataFrame(airbnb['address'])
a

                                                address
0     {'street': 'New York, NY, United States', 'sub...
1     {'street': 'Brooklyn, NY, United States', 'sub...
2     {'street': 'Rio de Janeiro, Rio de Janeiro, Br...
3     {'street': 'Rio de Janeiro, Rio de Janeiro, Br...
4     {'street': 'Montréal, Québec, Canada', 'suburb...
...                                                 ...
5550  {'street': 'Rio de Janeiro, Rio de Janeiro, Br...
5551  {'street': 'New York, NY, United States', 'sub...
5552  {'street': 'Bondi Beach, NSW, Australia', 'sub...
5553  {'street': 'Porto, Porto, Portugal', 'suburb':...
5554  {'street': 'Kadıköy, İstanbul, Turkey', 'subur...

[5555 rows x 1 columns]

In [39]:
a.to_csv('address_duplicate.csv', index=False)

In [40]:
address = pd.read_csv('address_duplicate.csv')
address

                                                address
0     {'street': 'New York, NY, United States', 'sub...
1     {'street': 'Brooklyn, NY, United States', 'sub...
2     {'street': 'Rio de Janeiro, Rio de Janeiro, Br...
3     {'street': 'Rio de Janeiro, Rio de Janeiro, Br...
4     {'street': 'Montréal, Québec, Canada', 'suburb...
...                                                 ...
5550  {'street': 'Rio de Janeiro, Rio de Janeiro, Br...
5551  {'street': 'New York, NY, United States', 'sub...
5552  {'street': 'Bondi Beach, NSW, Australia', 'sub...
5553  {'street': 'Porto, Porto, Portugal', 'suburb':...
5554  {'street': 'Kadıköy, İstanbul, Turkey', 'subur...

[5555 rows x 1 columns]

In [41]:
airbnb.address[1].keys()

dict_keys(['street', 'suburb', 'government_area', 'market', 'country', 'country_code', 'location'])

In [42]:
address = pd.DataFrame(a)


address['street'] = address['address'].apply(lambda x: x['street'])
address['suburb'] = address['address'].apply(lambda x: x['suburb'])
address['government_area'] = address['address'].apply(lambda x: x['government_area'])
address['market'] = address['address'].apply(lambda x: x['market'])
address['country'] = address['address'].apply(lambda x: x['country'])
address['country_code'] = address['address'].apply(lambda x: x['country_code'])
address['type'] = address['address'].apply(lambda x: x['location']['type'])
#address['coordinates'] = address['address'].apply(lambda x: x['location']['coordinates'])
address['Latitude'] = address['address'].apply(lambda x: x['location']['coordinates'][1])
address['Longitude'] = address['address'].apply(lambda x: x['location']['coordinates'][0])
address['is_location_exact'] = address['address'].apply(lambda x: x['location']['is_location_exact'])

# Drop the original 'address' column if not needed
address.drop(columns=['address'], inplace=True)

In [43]:
print(address['street'].value_counts())

Montréal, Québec, Canada                  492
Barcelona, Catalunya, Spain               427
Porto, Porto, Portugal                    351
Rio de Janeiro, Rio de Janeiro, Brazil    326
New York, NY, United States               284
                                         ...
Watsons Bay, NSW, Australia                 1
İstanbul, Kağıthane, Turkey                 1
Roseville, NSW, Australia                   1
causeway bay , causeway bay, Hong Kong      1
Waimanalo Beach, HI, United States          1
Name: street, Length: 677, dtype: int64

In [44]:
print(address['suburb'].value_counts())

                                 887
Copacabana                       154
Manhattan                        148
Eixample                         140
Brooklyn                         129
                                ...
Carmel                             1
Vilapicina i la Torre Llobeta      1
Waipahu                            1
Ridgewood                          1
Carlton                            1
Name: suburb, Length: 410, dtype: int64

In [45]:
address.duplicated().sum()

0

In [46]:
address = pd.DataFrame(address)

In [47]:
address.to_csv('address_duplicate.csv', index=False)

In [48]:
address = pd.read_csv('address_duplicate.csv')
address

,street,suburb,government_area,market,country,country_code,type,Latitude,Longitude,is_location_exact
0,"New York, NY, United States",Manhattan,Upper West Side,New York,United States,US,Point,40.799620,-73.965230,False
1,"Brooklyn, NY, United States",Greenpoint,Greenpoint,New York,United States,US,Point,40.727780,-73.944720,True
2,"Rio de Janeiro, Rio de Janeiro, Brazil",Catete,Catete,Rio De Janeiro,Brazil,BR,Point,-22.926382,-43.180157,True
3,"Rio de Janeiro, Rio de Janeiro, Brazil",Lagoa,Lagoa,Rio De Janeiro,Brazil,BR,Point,-22.971951,-43.205047,True
4,"Montréal, Québec, Canada",Hochelaga-Maisonneuve,Mercier-Hochelaga-Maisonneuve,Montreal,Canada,CA,Point,45.545480,-73.549490,False
...,...,...,...,...,...,...,...,...,...,...
5550,"Rio de Janeiro, Rio de Janeiro, Brazil",Copacabana,Copacabana,Rio De Janeiro,Brazil,BR,Point,-22.963806,-43.177922,False
5551,"New York, NY, United States",Manhattan,Upper East Side,New York,United States,US,Point,40.762660,-73.962050,True
5552,"Bondi Beach, NSW, Australia",Bondi,Waverley,Sydney,Australia,AU,Point,-33.892980,151.265420,False
5553,"Porto, Porto, Portugal",NaN,"Cedofeita, Ildefonso, Sé, Miragaia, Nicolau, V...",Porto,Portugal,PT,Point,41.151270,-8.606220,True
5554,"Kadıköy, İstanbul, Turkey",Moda,Kadikoy,Istanbul,Turkey,TR,Point,40.985630,29.030790,False

In [49]:
df = pd.read_csv('address_duplicate.csv')

# Split the 'street' column by comma and select the first part
#df['street'] = df['street'].str.split(',').str[0]
#df['government_area'] = df['government_area'].str.split(',').str[0]
#df = pd.DataFrame(data)

# Custom function to fill NaN values in 'suburb' using 'market'
def fill_suburb_with_market(row):
    if pd.isna(row['suburb']):
        return row['market']
    else:
        return row['suburb']

# Apply the custom function to fill NaN values in 'suburb' column
df['suburb'] = df.apply(fill_suburb_with_market, axis=1)

# Display the DataFrame with NaN values in 'suburb' filled using 'market'
#print(df)

In [50]:
df.loc[629, 'suburb'] = "Copacabana"

In [51]:
missing_values = df.isnull().sum()
#print("Missing Values:")
print(missing_values)

street               0
suburb               1
government_area      0
market               6
country              0
country_code         0
type                 0
Latitude             0
Longitude            0
is_location_exact    0
dtype: int64

In [52]:
missing_values = df[df['suburb'].isna()]

#Display the row(s) with missing value(s) in the 'suburb' column
print(missing_values)
#df.iloc[629]

                                     street suburb government_area market  \
640  Rio de Janeiro, Rio de Janeiro, Brazil    NaN      Copacabana    NaN

    country country_code   type   Latitude  Longitude  is_location_exact
640  Brazil           BR  Point -22.975668  -43.19012               True

In [53]:
df.loc[640, 'suburb'] = "Copacabana"

In [54]:
df["suburb"]

0                   Manhattan
1                  Greenpoint
2                      Catete
3                       Lagoa
4       Hochelaga-Maisonneuve
                ...
5550               Copacabana
5551                Manhattan
5552                    Bondi
5553                    Porto
5554                     Moda
Name: suburb, Length: 5555, dtype: object

In [55]:
missing_values = df[df['market'].isna()]

#Display the row(s) with missing value(s) in the 'suburb' column
print(missing_values)
#df.iloc[629]

                                     street             suburb  \
583                Waverley, NSW, Australia            Waverly
605             New York, NY, United States          Manhattan
640  Rio de Janeiro, Rio de Janeiro, Brazil         Copacabana
667                Montréal, Québec, Canada  Downtown Montreal
781             Barcelona, Catalunya, Spain     Sants-Montjuïc
810                Kapaa, HI, United States             Kauaʻi

     government_area market        country country_code   type   Latitude  \
583         Waverley    NaN      Australia           AU  Point -33.902980
605  Upper West Side    NaN  United States           US  Point  40.794150
640       Copacabana    NaN         Brazil           BR  Point -22.975668
667      Ville-Marie    NaN         Canada           CA  Point  45.525880
781     el Poble Sec    NaN          Spain           ES  Point  41.372070
810     Kapaa-Wailua    NaN  United States           US  Point  22.053230

     Longitude  is_location_exact
583  151.25337               True
605  -73.97323               True
640  -43.19012               True
667  -73.55997               True
781    2.15659               True
810 -159.32794               True

In [56]:
df.loc[583, 'market'] = "Québec"
df.loc[605, 'market'] = "Copacabana"
df.loc[640, 'market'] = " Waverly"
df.loc[667, 'market'] = "Manhattan"
df.loc[781, 'market'] = "Sants-Montjuïc"
df.loc[810, 'market'] = "Kauaʻi"

In [57]:
missing_values = df.isnull().sum()
#print("Missing Values:")
print(missing_values)

street               0
suburb               0
government_area      0
market               0
country              0
country_code         0
type                 0
Latitude             0
Longitude            0
is_location_exact    0
dtype: int64

In [58]:
df['street'] = df['street'].str.split(',').str[0]

In [59]:
df['government_area'] = df['government_area'].str.split(',').str[0]

In [60]:
df

,street,suburb,government_area,market,country,country_code,type,Latitude,Longitude,is_location_exact
0,New York,Manhattan,Upper West Side,New York,United States,US,Point,40.799620,-73.965230,False
1,Brooklyn,Greenpoint,Greenpoint,New York,United States,US,Point,40.727780,-73.944720,True
2,Rio de Janeiro,Catete,Catete,Rio De Janeiro,Brazil,BR,Point,-22.926382,-43.180157,True
3,Rio de Janeiro,Lagoa,Lagoa,Rio De Janeiro,Brazil,BR,Point,-22.971951,-43.205047,True
4,Montréal,Hochelaga-Maisonneuve,Mercier-Hochelaga-Maisonneuve,Montreal,Canada,CA,Point,45.545480,-73.549490,False
...,...,...,...,...,...,...,...,...,...,...
5550,Rio de Janeiro,Copacabana,Copacabana,Rio De Janeiro,Brazil,BR,Point,-22.963806,-43.177922,False
5551,New York,Manhattan,Upper East Side,New York,United States,US,Point,40.762660,-73.962050,True
5552,Bondi Beach,Bondi,Waverley,Sydney,Australia,AU,Point,-33.892980,151.265420,False
5553,Porto,Porto,Cedofeita,Porto,Portugal,PT,Point,41.151270,-8.606220,True
5554,Kadıköy,Moda,Kadikoy,Istanbul,Turkey,TR,Point,40.985630,29.030790,False

In [61]:
df.to_csv('address_main.csv', index=False)

#                     HOST

In [62]:
b = pd.DataFrame(airbnb['host'])
b

                                                   host
0     {'host_id': '454250', 'host_url': 'https://www...
1     {'host_id': '47554473', 'host_url': 'https://w...
2     {'host_id': '51326285', 'host_url': 'https://w...
3     {'host_id': '51496939', 'host_url': 'https://w...
4     {'host_id': '7140229', 'host_url': 'https://ww...
...                                                 ...
5550  {'host_id': '1403065', 'host_url': 'https://ww...
5551  {'host_id': '40540485', 'host_url': 'https://w...
5552  {'host_id': '47615848', 'host_url': 'https://w...
5553  {'host_id': '2296185', 'host_url': 'https://ww...
5554  {'host_id': '51303748', 'host_url': 'https://w...

[5555 rows x 1 columns]

In [63]:
b['host'][0]

{'host_id': '454250',
 'host_url': 'https://www.airbnb.com/users/show/454250',
 'host_name': 'Greta',
 'host_location': 'New York, New York, United States',
 'host_about': 'By now I have lived longer in the city than the country however I feel equally at home in each. I like to keep one foot in each and help others to do the same!',
 'host_response_time': 'within an hour',
 'host_thumbnail_url': 'https://a0.muscache.com/im/pictures/f1022be4-e72a-4b35-b6d2-3d2736ddaff9.jpg?aki_policy=profile_small',
 'host_picture_url': 'https://a0.muscache.com/im/pictures/f1022be4-e72a-4b35-b6d2-3d2736ddaff9.jpg?aki_policy=profile_x_medium',
 'host_neighbourhood': '',
 'host_response_rate': 100,
 'host_is_superhost': True,
 'host_has_profile_pic': True,
 'host_identity_verified': True,
 'host_listings_count': 3,
 'host_total_listings_count': 3,
 'host_verifications': ['email',
  'phone',
  'reviews',
  'jumio',
  'offline_government_id',
  'government_id']}

In [64]:
host = pd.DataFrame(b)

# Extract 'host_id' and 'host_name' from 'host' dictionary
host['host_id'] = host['host'].apply(lambda x: x['host_id'])
host['host_url'] = host['host'].apply(lambda x: x['host_url'])
host['host_name'] = host['host'].apply(lambda x: x['host_name'])
host['host_location'] = host['host'].apply(lambda x: x['host_location'])
host['host_about'] = host['host'].apply(lambda x: x['host_about'])
host['host_response_time'] = host['host'].apply(lambda x: x.get('host_response_time','null'))
host['host_thumbnail_urlt'] = host['host'].apply(lambda x: x['host_thumbnail_url'])
host['host_picture_url'] = host['host'].apply(lambda x: x['host_picture_url'])
host['host_neighbourhood'] = host['host'].apply(lambda x: x['host_neighbourhood'])
host['host_response_rate'] = host['host'].apply(lambda x: x.get('host_response_rate',0))
host['host_is_superhost'] = host['host'].apply(lambda x: x['host_is_superhost'])
host['host_has_profile_pic'] = host['host'].apply(lambda x: x['host_has_profile_pic'])
host['host_identity_verified'] = host['host'].apply(lambda x: x['host_identity_verified'])
host['host_listings_count'] = host['host'].apply(lambda x: x['host_listings_count'])
host['host_total_listings_count'] = host['host'].apply(lambda x: x['host_total_listings_count'])
#host['host_verifications'] = host['host']['host_verifications'].apply(len)
host['host_verifications'] = host['host'].apply(lambda x: x['host_verifications'])
host['host_verifications'] = host['host_verifications'].apply(len)
# Drop the original 'host' column if not needed
host.drop(columns=['host'], inplace=True)

# Display the updated DataFrame
#print(host)

In [65]:
host[host['host_id'] == 53319251]

Empty DataFrame
Columns: [host_id, host_url, host_name, host_location, host_about, host_response_time, host_thumbnail_urlt, host_picture_url, host_neighbourhood, host_response_rate, host_is_superhost, host_has_profile_pic, host_identity_verified, host_listings_count, host_total_listings_count, host_verifications]
Index: []

In [66]:
print(host['host_response_time'].value_counts())
print(host['host_response_rate'].value_counts())

within an hour        2715
null                  1388
within a few hours     742
within a day           566
a few days or more     144
Name: host_response_time, dtype: int64
100    2952
0      1485
90      133
98      109
99      104
       ...
47        1
17        1
42        1
30        1
84        1
Name: host_response_rate, Length: 62, dtype: int64

In [67]:
host.drop_duplicates(inplace=True)

In [68]:
host.describe()

,host_response_rate,host_listings_count,host_total_listings_count,host_verifications
count,5104.000000,5104.000000,5104.000000,5104.000000
mean,67.681034,7.173589,7.173589,4.906544
std,44.405540,30.484584,30.484584,2.180131
min,0.000000,0.000000,0.000000,1.000000
25%,0.000000,1.000000,1.000000,3.000000
50%,100.000000,2.000000,2.000000,5.000000
75%,100.000000,4.000000,4.000000,6.000000
max,100.000000,1198.000000,1198.000000,12.000000

In [69]:
Q1 = host['host_response_rate'].quantile(0.25)
Q3 = host['host_response_rate'].quantile(0.75)
IQR = Q3 - Q1

# Define the lower and upper bounds for outlier detection
lower_bound = Q1 - (1.5 * IQR)
upper_bound = Q3 + (1.5 * IQR)


lower_bound ,upper_bound

#print(outliers)

(-150.0, 250.0)

In [70]:
host.host_response_rate = host.host_response_rate.clip(upper_bound , lower_bound )

In [71]:
Q1 = host['host_listings_count'].quantile(0.25)
Q3 = host['host_listings_count'].quantile(0.75)
IQR = Q3 - Q1

# Define the lower and upper bounds for outlier detection
lower_bound = Q1 - (1.5 * IQR)
upper_bound = Q3 + (1.5 * IQR)


lower_bound ,upper_bound

#print(outliers)

(-3.5, 8.5)

In [72]:
host.host_total_listings_count = host.host_total_listings_count.clip(upper_bound , lower_bound )

In [73]:
Q1 = host['host_verifications'].quantile(0.25)
Q3 = host['host_verifications'].quantile(0.75)
IQR = Q3 - Q1

# Define the lower and upper bounds for outlier detection
lower_bound = Q1 - (1.5 * IQR)
upper_bound = Q3 + (1.5 * IQR)


lower_bound ,upper_bound

#print(outliers)

(-1.5, 10.5)

In [74]:
host.host_verifications = host.host_verifications.clip(upper_bound , lower_bound )

In [75]:
host = pd.DataFrame(host)
host

,host_id,host_url,host_name,host_location,host_about,host_response_time,host_thumbnail_urlt,host_picture_url,host_neighbourhood,host_response_rate,host_is_superhost,host_has_profile_pic,host_identity_verified,host_listings_count,host_total_listings_count,host_verifications
0,454250,https://www.airbnb.com/users/show/454250,Greta,"New York, New York, United States",By now I have lived longer in the city than th...,within an hour,https://a0.muscache.com/im/pictures/f1022be4-e...,https://a0.muscache.com/im/pictures/f1022be4-e...,,100,True,True,True,3,3.0,6.0
1,47554473,https://www.airbnb.com/users/show/47554473,Mae,US,,within a few hours,https://a0.muscache.com/im/pictures/c680ce22-d...,https://a0.muscache.com/im/pictures/c680ce22-d...,Greenpoint,100,False,True,False,13,8.5,6.0
2,51326285,https://www.airbnb.com/users/show/51326285,Beatriz,"Rio de Janeiro, State of Rio de Janeiro, Brazil",,within an hour,https://a0.muscache.com/im/pictures/eb09c9cb-b...,https://a0.muscache.com/im/pictures/eb09c9cb-b...,Catete,80,False,True,True,5,5.0,6.0
3,51496939,https://www.airbnb.com/users/show/51496939,Livia,BR,,null,https://a0.muscache.com/im/pictures/b7911710-9...,https://a0.muscache.com/im/pictures/b7911710-9...,Lagoa,0,False,True,False,1,1.0,4.0
4,7140229,https://www.airbnb.com/users/show/7140229,Caro,"Montreal, Quebec, Canada",,within an hour,https://a0.muscache.com/im/pictures/user/c6477...,https://a0.muscache.com/im/pictures/user/c6477...,,100,False,True,False,1,1.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5550,1403065,https://www.airbnb.com/users/show/1403065,Clarissa,"Rio de Janeiro, Rio de Janeiro, Brazil","I am Brazilian, 39 y.o. live in Rio de Janeiro...",within an hour,https://a0.muscache.com/im/pictures/8bd5fd4e-3...,https://a0.muscache.com/im/pictures/8bd5fd4e-3...,,100,False,True,False,2,2.0,4.0
5551,40540485,https://www.airbnb.com/users/show/40540485,Miguel,"New York, New York, United States",We are a married couple who loves to travel ev...,within an hour,https://a0.muscache.com/im/pictures/f2065606-7...,https://a0.muscache.com/im/pictures/f2065606-7...,Upper East Side,100,False,True,True,1,1.0,5.0
5552,47615848,https://www.airbnb.com/users/show/47615848,Lucy,"Bondi Beach, New South Wales, Australia",,null,https://a0.muscache.com/im/pictures/b4675d0a-f...,https://a0.muscache.com/im/pictures/b4675d0a-f...,,0,False,True,False,1,1.0,2.0
5553,2296185,https://www.airbnb.com/users/show/2296185,Manuel,"Jovim, Porto, Portugal",From Porto,within a few hours,https://a0.muscache.com/im/users/2296185/profi...,https://a0.muscache.com/im/users/2296185/profi...,,90,False,True,True,3,3.0,6.0
5554,51303748,https://www.airbnb.com/users/show/51303748,Eren,"Kadikoy, Çanakkale, Turkey",,null,https://a0.muscache.com/im/pictures/89a1b839-2...,https://a0.muscache.com/im/pictures/89a1b839-2...,,0,False,True,False,2,2.0,2.0

In [76]:
host.to_csv('host_duplicates.csv', index=False)

In [77]:
df_1 = pd.read_csv('host_duplicates.csv')
df_1

,host_id,host_url,host_name,host_location,host_about,host_response_time,host_thumbnail_urlt,host_picture_url,host_neighbourhood,host_response_rate,host_is_superhost,host_has_profile_pic,host_identity_verified,host_listings_count,host_total_listings_count,host_verifications
0,454250,https://www.airbnb.com/users/show/454250,Greta,"New York, New York, United States",By now I have lived longer in the city than th...,within an hour,https://a0.muscache.com/im/pictures/f1022be4-e...,https://a0.muscache.com/im/pictures/f1022be4-e...,NaN,100,True,True,True,3,3.0,6.0
1,47554473,https://www.airbnb.com/users/show/47554473,Mae,US,NaN,within a few hours,https://a0.muscache.com/im/pictures/c680ce22-d...,https://a0.muscache.com/im/pictures/c680ce22-d...,Greenpoint,100,False,True,False,13,8.5,6.0
2,51326285,https://www.airbnb.com/users/show/51326285,Beatriz,"Rio de Janeiro, State of Rio de Janeiro, Brazil",NaN,within an hour,https://a0.muscache.com/im/pictures/eb09c9cb-b...,https://a0.muscache.com/im/pictures/eb09c9cb-b...,Catete,80,False,True,True,5,5.0,6.0
3,51496939,https://www.airbnb.com/users/show/51496939,Livia,BR,NaN,NaN,https://a0.muscache.com/im/pictures/b7911710-9...,https://a0.muscache.com/im/pictures/b7911710-9...,Lagoa,0,False,True,False,1,1.0,4.0
4,7140229,https://www.airbnb.com/users/show/7140229,Caro,"Montreal, Quebec, Canada",NaN,within an hour,https://a0.muscache.com/im/pictures/user/c6477...,https://a0.muscache.com/im/pictures/user/c6477...,NaN,100,False,True,False,1,1.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5099,1403065,https://www.airbnb.com/users/show/1403065,Clarissa,"Rio de Janeiro, Rio de Janeiro, Brazil","I am Brazilian, 39 y.o. live in Rio de Janeiro...",within an hour,https://a0.muscache.com/im/pictures/8bd5fd4e-3...,https://a0.muscache.com/im/pictures/8bd5fd4e-3...,NaN,100,False,True,False,2,2.0,4.0
5100,40540485,https://www.airbnb.com/users/show/40540485,Miguel,"New York, New York, United States",We are a married couple who loves to travel ev...,within an hour,https://a0.muscache.com/im/pictures/f2065606-7...,https://a0.muscache.com/im/pictures/f2065606-7...,Upper East Side,100,False,True,True,1,1.0,5.0
5101,47615848,https://www.airbnb.com/users/show/47615848,Lucy,"Bondi Beach, New South Wales, Australia",NaN,NaN,https://a0.muscache.com/im/pictures/b4675d0a-f...,https://a0.muscache.com/im/pictures/b4675d0a-f...,NaN,0,False,True,False,1,1.0,2.0
5102,2296185,https://www.airbnb.com/users/show/2296185,Manuel,"Jovim, Porto, Portugal",From Porto,within a few hours,https://a0.muscache.com/im/users/2296185/profi...,https://a0.muscache.com/im/users/2296185/profi...,NaN,90,False,True,True,3,3.0,6.0
5103,51303748,https://www.airbnb.com/users/show/51303748,Eren,"Kadikoy, Çanakkale, Turkey",NaN,NaN,https://a0.muscache.com/im/pictures/89a1b839-2...,https://a0.muscache.com/im/pictures/89a1b839-2...,NaN,0,False,True,False,2,2.0,2.0

In [78]:
df_1.columns

Index(['host_id', 'host_url', 'host_name', 'host_location', 'host_about',
       'host_response_time', 'host_thumbnail_urlt', 'host_picture_url',
       'host_neighbourhood', 'host_response_rate', 'host_is_superhost',
       'host_has_profile_pic', 'host_identity_verified', 'host_listings_count',
       'host_total_listings_count', 'host_verifications'],
      dtype='object')

In [79]:
df_1.drop(columns=['host_neighbourhood'], inplace=True)

In [80]:
missing_values = df_1.isnull().sum()
#print("Missing Values:")
print(missing_values)

host_id                         0
host_url                        0
host_name                       0
host_location                   8
host_about                   2139
host_response_time           1381
host_thumbnail_urlt             0
host_picture_url                0
host_response_rate              0
host_is_superhost               0
host_has_profile_pic            0
host_identity_verified          0
host_listings_count             0
host_total_listings_count       0
host_verifications              0
dtype: int64

In [81]:
df_1.drop(columns=['host_response_time'], inplace=True)

In [82]:
df_1['host_location'].fillna(df_1['host_location'].mode(), inplace=True)

In [83]:
df_1.dropna(subset=['host_location'],inplace=True)

In [84]:
missing_values = df_1.isnull().sum()
#print("Missing Values:")
print(missing_values)

host_id                         0
host_url                        0
host_name                       0
host_location                   0
host_about                   2131
host_thumbnail_urlt             0
host_picture_url                0
host_response_rate              0
host_is_superhost               0
host_has_profile_pic            0
host_identity_verified          0
host_listings_count             0
host_total_listings_count       0
host_verifications              0
dtype: int64

In [85]:
df_1

,host_id,host_url,host_name,host_location,host_about,host_thumbnail_urlt,host_picture_url,host_response_rate,host_is_superhost,host_has_profile_pic,host_identity_verified,host_listings_count,host_total_listings_count,host_verifications
0,454250,https://www.airbnb.com/users/show/454250,Greta,"New York, New York, United States",By now I have lived longer in the city than th...,https://a0.muscache.com/im/pictures/f1022be4-e...,https://a0.muscache.com/im/pictures/f1022be4-e...,100,True,True,True,3,3.0,6.0
1,47554473,https://www.airbnb.com/users/show/47554473,Mae,US,NaN,https://a0.muscache.com/im/pictures/c680ce22-d...,https://a0.muscache.com/im/pictures/c680ce22-d...,100,False,True,False,13,8.5,6.0
2,51326285,https://www.airbnb.com/users/show/51326285,Beatriz,"Rio de Janeiro, State of Rio de Janeiro, Brazil",NaN,https://a0.muscache.com/im/pictures/eb09c9cb-b...,https://a0.muscache.com/im/pictures/eb09c9cb-b...,80,False,True,True,5,5.0,6.0
3,51496939,https://www.airbnb.com/users/show/51496939,Livia,BR,NaN,https://a0.muscache.com/im/pictures/b7911710-9...,https://a0.muscache.com/im/pictures/b7911710-9...,0,False,True,False,1,1.0,4.0
4,7140229,https://www.airbnb.com/users/show/7140229,Caro,"Montreal, Quebec, Canada",NaN,https://a0.muscache.com/im/pictures/user/c6477...,https://a0.muscache.com/im/pictures/user/c6477...,100,False,True,False,1,1.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5099,1403065,https://www.airbnb.com/users/show/1403065,Clarissa,"Rio de Janeiro, Rio de Janeiro, Brazil","I am Brazilian, 39 y.o. live in Rio de Janeiro...",https://a0.muscache.com/im/pictures/8bd5fd4e-3...,https://a0.muscache.com/im/pictures/8bd5fd4e-3...,100,False,True,False,2,2.0,4.0
5100,40540485,https://www.airbnb.com/users/show/40540485,Miguel,"New York, New York, United States",We are a married couple who loves to travel ev...,https://a0.muscache.com/im/pictures/f2065606-7...,https://a0.muscache.com/im/pictures/f2065606-7...,100,False,True,True,1,1.0,5.0
5101,47615848,https://www.airbnb.com/users/show/47615848,Lucy,"Bondi Beach, New South Wales, Australia",NaN,https://a0.muscache.com/im/pictures/b4675d0a-f...,https://a0.muscache.com/im/pictures/b4675d0a-f...,0,False,True,False,1,1.0,2.0
5102,2296185,https://www.airbnb.com/users/show/2296185,Manuel,"Jovim, Porto, Portugal",From Porto,https://a0.muscache.com/im/users/2296185/profi...,https://a0.muscache.com/im/users/2296185/profi...,90,False,True,True,3,3.0,6.0
5103,51303748,https://www.airbnb.com/users/show/51303748,Eren,"Kadikoy, Çanakkale, Turkey",NaN,https://a0.muscache.com/im/pictures/89a1b839-2...,https://a0.muscache.com/im/pictures/89a1b839-2...,0,False,True,False,2,2.0,2.0

In [86]:
df_1.to_csv('host_main.csv', index=False)

In [87]:
c = pd.DataFrame(airbnb['amenities'])
c

                                              amenities
0     [Internet, Wifi, Air conditioning, Kitchen, El...
1     [TV, Cable TV, Internet, Wifi, Air conditionin...
2     [TV, Cable TV, Internet, Wifi, Air conditionin...
3     [TV, Cable TV, Internet, Wifi, Air conditionin...
4     [TV, Internet, Wifi, Kitchen, Free parking on ...
...                                                 ...
5550  [TV, Cable TV, Internet, Wifi, Air conditionin...
5551  [Wifi, Air conditioning, Kitchen, Pets allowed...
5552  [TV, Internet, Wifi, Kitchen, Washer, Dryer, S...
5553  [TV, Cable TV, Wifi, Kitchen, Elevator, Heatin...
5554  [TV, Cable TV, Internet, Wifi, Kitchen, Buzzer...

[5555 rows x 1 columns]

In [88]:
amenities = pd.DataFrame(c)

# Calculate lengths of each 'amenities' list and create a new column
amenities['amenities_length'] = amenities['amenities'].apply(len)

# Print the DataFrame
#print(amenities)
amenities = amenities.drop(columns=['amenities'])
amenities= pd.DataFrame(amenities)
amenities

      amenities_length
0                   11
1                   23
2                   11
3                   16
4                   13
...                ...
5550                21
5551                32
5552                 9
5553                15
5554                15

[5555 rows x 1 columns]

In [89]:
amenities.to_csv('amenities', index=False)

In [90]:
df_2 = pd.read_csv('amenities')
df_2

      amenities_length
0                   11
1                   23
2                   11
3                   16
4                   13
...                ...
5550                21
5551                32
5552                 9
5553                15
5554                15

[5555 rows x 1 columns]

In [91]:
d=pd.DataFrame(airbnb['availability'])
d

                                           availability
0     {'availability_30': 0, 'availability_60': 0, '...
1     {'availability_30': 30, 'availability_60': 31,...
2     {'availability_30': 10, 'availability_60': 10,...
3     {'availability_30': 28, 'availability_60': 58,...
4     {'availability_30': 0, 'availability_60': 0, '...
...                                                 ...
5550  {'availability_30': 17, 'availability_60': 35,...
5551  {'availability_30': 2, 'availability_60': 11, ...
5552  {'availability_30': 0, 'availability_60': 0, '...
5553  {'availability_30': 28, 'availability_60': 54,...
5554  {'availability_30': 30, 'availability_60': 60,...

[5555 rows x 1 columns]

In [92]:
d['availability'][0]

{'availability_30': 0,
 'availability_60': 0,
 'availability_90': 0,
 'availability_365': 93}

In [93]:
availability = pd.DataFrame(d)

availability['availability_30'] = availability['availability'].apply(lambda x: x['availability_30'])
availability['availability_60'] = availability['availability'].apply(lambda x: x['availability_60'])
availability['availability_90'] = availability['availability'].apply(lambda x: x['availability_90'])
availability['availability_365'] = availability['availability'].apply(lambda x: x['availability_365'])

availability.drop(columns=['availability'], inplace=True)

In [94]:
availability.isnull().sum()

availability_30     0
availability_60     0
availability_90     0
availability_365    0
dtype: int64

In [95]:
availability.duplicated().sum()

2684

In [96]:
availability.drop_duplicates(inplace=True)

In [97]:
availability.describe()

       availability_30  availability_60  availability_90  availability_365
count      2871.000000      2871.000000      2871.000000       2871.000000
mean         11.082201        26.251480        44.379659        200.592825
std           9.312137        17.874499        25.998366        108.597234
min           0.000000         0.000000         0.000000          0.000000
25%           3.000000        11.000000        23.000000        100.500000
50%           9.000000        25.000000        46.000000        216.000000
75%          18.000000        41.000000        66.000000        300.500000
max          30.000000        60.000000        90.000000        365.000000

In [98]:
Q1 = availability['availability_30'].quantile(0.25)
Q3 = availability['availability_30'].quantile(0.75)
IQR = Q3 - Q1

# Define the lower and upper bounds for outlier detection
lower_bound = Q1 - (1.5 * IQR)
upper_bound = Q3 + (1.5 * IQR)


print(lower_bound ,upper_bound)

-19.5 40.5

In [99]:
availability.availability_30 = availability.availability_30.clip(upper_bound , lower_bound )

In [100]:
Q1 = availability['availability_60'].quantile(0.25)
Q3 = availability['availability_60'].quantile(0.75)
IQR = Q3 - Q1

# Define the lower and upper bounds for outlier detection
lower_bound = Q1 - (1.5 * IQR)
upper_bound = Q3 + (1.5 * IQR)
print(lower_bound ,upper_bound)

-34.0 86.0

In [101]:
availability.availability_60 = availability.availability_60.clip(upper_bound , lower_bound )

In [102]:
Q1 = availability['availability_90'].quantile(0.25)
Q3 = availability['availability_90'].quantile(0.75)
IQR = Q3 - Q1

# Define the lower and upper bounds for outlier detection
lower_bound = Q1 - (1.5 * IQR)
upper_bound = Q3 + (1.5 * IQR)
print(lower_bound ,upper_bound)

-41.5 130.5

In [103]:
availability.availability_90 = availability.availability_90.clip(upper_bound , lower_bound)

In [104]:
Q1 = availability['availability_365'].quantile(0.25)
Q3 = availability['availability_365'].quantile(0.75)
IQR = Q3 - Q1

# Define the lower and upper bounds for outlier detection
lower_bound = Q1 - (1.5 * IQR)
upper_bound = Q3 + (1.5 * IQR)
print(lower_bound ,upper_bound)

-199.5 600.5

In [105]:
availability.availability_365 = availability.availability_365.clip(upper_bound , lower_bound )

In [106]:
availability = pd.DataFrame(availability)
availability

      availability_30  availability_60  availability_90  availability_365
0                   0                0                0                93
1                  30               31               31               243
2                  10               10               21               296
3                  28               58               88               363
4                   0                0                0                32
...               ...              ...              ...               ...
5548                0               15               28               212
5549                0                0                0               139
5550               17               35               63               322
5551                2               11               15               154
5553               28               54               82               351

[2871 rows x 4 columns]

In [107]:
df_3=availability.copy()
df_3

      availability_30  availability_60  availability_90  availability_365
0                   0                0                0                93
1                  30               31               31               243
2                  10               10               21               296
3                  28               58               88               363
4                   0                0                0                32
...               ...              ...              ...               ...
5548                0               15               28               212
5549                0                0                0               139
5550               17               35               63               322
5551                2               11               15               154
5553               28               54               82               351

[2871 rows x 4 columns]

In [108]:
missing_values = df_3.isnull().sum()
#print("Missing Values:")
print(missing_values)

availability_30     0
availability_60     0
availability_90     0
availability_365    0
dtype: int64

In [109]:
e = pd.DataFrame(airbnb['review_scores'])
e

                                          review_scores
0     {'review_scores_accuracy': 10, 'review_scores_...
1     {'review_scores_accuracy': 9, 'review_scores_c...
2     {'review_scores_accuracy': 10, 'review_scores_...
3                                                    {}
4                                                    {}
...                                                 ...
5550  {'review_scores_accuracy': 10, 'review_scores_...
5551  {'review_scores_accuracy': 9, 'review_scores_c...
5552                                                 {}
5553  {'review_scores_accuracy': 9, 'review_scores_c...
5554                                                 {}

[5555 rows x 1 columns]

In [110]:
rating = pd.DataFrame(e)

# Extract review scores from nested 'review_scores' dictionary
rating['review_scores_accuracy'] = rating['review_scores'].apply(lambda x: x.get('review_scores_accuracy',0))
rating['review_scores_cleanliness'] = rating['review_scores'].apply(lambda x: x.get('review_scores_cleanliness',0))
rating['review_scores_checkin'] = rating['review_scores'].apply(lambda x: x.get('review_scores_checkin',0))
rating['review_scores_communication'] = rating['review_scores'].apply(lambda x: x.get('review_scores_communication',0))
rating['review_scores_location'] = rating['review_scores'].apply(lambda x: x.get('review_scores_location',0))
rating['review_scores_value'] = rating['review_scores'].apply(lambda x: x.get('review_scores_value',0))
rating['review_scores_rating'] = rating['review_scores'].apply(lambda x: x.get('review_scores_rating',0))

# Drop the original 'review_scores' column if not needed
rating.drop(columns=['review_scores'], inplace=True)

In [111]:
rating.to_csv('rating_dup', index = False)

In [112]:
df_4 = pd.read_csv("rating_dup")
df_4

,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,review_scores_rating
0,10,9,10,10,10,10,94
1,9,10,10,8,9,9,88
2,10,6,8,8,8,8,80
3,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...
5550,10,10,10,10,10,10,97
5551,9,9,10,10,10,9,92
5552,0,0,0,0,0,0,0
5553,9,9,9,9,9,8,89
5554,0,0,0,0,0,0,0

In [113]:
df_4.isnull().sum()

review_scores_accuracy         0
review_scores_cleanliness      0
review_scores_checkin          0
review_scores_communication    0
review_scores_location         0
review_scores_value            0
review_scores_rating           0
dtype: int64

In [114]:
df_4.duplicated().sum()

4391

In [115]:
df_4.drop_duplicates(inplace=True)

In [116]:
airbnb_1

,name,property_type,room_type,bed_type,minimum_nights,maximum_nights,cancellation_policy,accommodates,bedrooms,beds,number_of_reviews,bathrooms,price,extra_people,guests_included
0,New York City - Upper West Side Apt,Apartment,Private room,Real Bed,6.0,360,strict_14_with_grace_period,2.0,1,1.0,70,1.0,135.0,0,1
1,Deluxe Loft Suite,Apartment,Entire home/apt,Real Bed,3.0,1125,strict_14_with_grace_period,3.5,0,2.0,5,1.0,205.0,0,1
2,Catete's Colonial Big Hause Room B,House,Private room,Real Bed,2.0,1125,strict_14_with_grace_period,3.5,1,6.0,1,1.0,250.0,40,4
3,Apt Linda Vista Lagoa - Rio,Apartment,Private room,Real Bed,1.0,1125,flexible,2.0,1,1.0,0,1.0,701.0,0,1
4,Ligne verte - à 15 min de métro du centre ville.,Apartment,Entire home/apt,Real Bed,2.0,1125,moderate,2.0,0,1.0,0,1.0,43.0,12,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5550,Lindo apto quarto e sala ao lado do mar de Copa!,Apartment,Entire home/apt,Real Bed,2.0,1125,strict_14_with_grace_period,3.5,1,2.0,19,1.0,119.0,0,1
5551,Beautiful Place in the Middle of Manhattan,Apartment,Entire home/apt,Real Bed,1.0,1125,strict_14_with_grace_period,2.0,1,1.0,180,1.0,160.0,20,2
5552,Large double room in Bondi,Apartment,Private room,Real Bed,3.0,1125,moderate,2.0,1,1.0,0,1.0,60.0,50,2
5553,StayIN Oporto Música - Apartment,Apartment,Entire home/apt,Real Bed,1.0,1125,strict_14_with_grace_period,3.5,8,6.0,20,1.0,500.0,30,16
5554,Kadıköy-Altıyol,House,Entire home/apt,Real Bed,1.0,1125,flexible,2.0,2,3.0,0,1.0,501.0,0,1

In [117]:
df #address

,street,suburb,government_area,market,country,country_code,type,Latitude,Longitude,is_location_exact
0,New York,Manhattan,Upper West Side,New York,United States,US,Point,40.799620,-73.965230,False
1,Brooklyn,Greenpoint,Greenpoint,New York,United States,US,Point,40.727780,-73.944720,True
2,Rio de Janeiro,Catete,Catete,Rio De Janeiro,Brazil,BR,Point,-22.926382,-43.180157,True
3,Rio de Janeiro,Lagoa,Lagoa,Rio De Janeiro,Brazil,BR,Point,-22.971951,-43.205047,True
4,Montréal,Hochelaga-Maisonneuve,Mercier-Hochelaga-Maisonneuve,Montreal,Canada,CA,Point,45.545480,-73.549490,False
...,...,...,...,...,...,...,...,...,...,...
5550,Rio de Janeiro,Copacabana,Copacabana,Rio De Janeiro,Brazil,BR,Point,-22.963806,-43.177922,False
5551,New York,Manhattan,Upper East Side,New York,United States,US,Point,40.762660,-73.962050,True
5552,Bondi Beach,Bondi,Waverley,Sydney,Australia,AU,Point,-33.892980,151.265420,False
5553,Porto,Porto,Cedofeita,Porto,Portugal,PT,Point,41.151270,-8.606220,True
5554,Kadıköy,Moda,Kadikoy,Istanbul,Turkey,TR,Point,40.985630,29.030790,False

In [118]:
df_1  #host

,host_id,host_url,host_name,host_location,host_about,host_thumbnail_urlt,host_picture_url,host_response_rate,host_is_superhost,host_has_profile_pic,host_identity_verified,host_listings_count,host_total_listings_count,host_verifications
0,454250,https://www.airbnb.com/users/show/454250,Greta,"New York, New York, United States",By now I have lived longer in the city than th...,https://a0.muscache.com/im/pictures/f1022be4-e...,https://a0.muscache.com/im/pictures/f1022be4-e...,100,True,True,True,3,3.0,6.0
1,47554473,https://www.airbnb.com/users/show/47554473,Mae,US,NaN,https://a0.muscache.com/im/pictures/c680ce22-d...,https://a0.muscache.com/im/pictures/c680ce22-d...,100,False,True,False,13,8.5,6.0
2,51326285,https://www.airbnb.com/users/show/51326285,Beatriz,"Rio de Janeiro, State of Rio de Janeiro, Brazil",NaN,https://a0.muscache.com/im/pictures/eb09c9cb-b...,https://a0.muscache.com/im/pictures/eb09c9cb-b...,80,False,True,True,5,5.0,6.0
3,51496939,https://www.airbnb.com/users/show/51496939,Livia,BR,NaN,https://a0.muscache.com/im/pictures/b7911710-9...,https://a0.muscache.com/im/pictures/b7911710-9...,0,False,True,False,1,1.0,4.0
4,7140229,https://www.airbnb.com/users/show/7140229,Caro,"Montreal, Quebec, Canada",NaN,https://a0.muscache.com/im/pictures/user/c6477...,https://a0.muscache.com/im/pictures/user/c6477...,100,False,True,False,1,1.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5099,1403065,https://www.airbnb.com/users/show/1403065,Clarissa,"Rio de Janeiro, Rio de Janeiro, Brazil","I am Brazilian, 39 y.o. live in Rio de Janeiro...",https://a0.muscache.com/im/pictures/8bd5fd4e-3...,https://a0.muscache.com/im/pictures/8bd5fd4e-3...,100,False,True,False,2,2.0,4.0
5100,40540485,https://www.airbnb.com/users/show/40540485,Miguel,"New York, New York, United States",We are a married couple who loves to travel ev...,https://a0.muscache.com/im/pictures/f2065606-7...,https://a0.muscache.com/im/pictures/f2065606-7...,100,False,True,True,1,1.0,5.0
5101,47615848,https://www.airbnb.com/users/show/47615848,Lucy,"Bondi Beach, New South Wales, Australia",NaN,https://a0.muscache.com/im/pictures/b4675d0a-f...,https://a0.muscache.com/im/pictures/b4675d0a-f...,0,False,True,False,1,1.0,2.0
5102,2296185,https://www.airbnb.com/users/show/2296185,Manuel,"Jovim, Porto, Portugal",From Porto,https://a0.muscache.com/im/users/2296185/profi...,https://a0.muscache.com/im/users/2296185/profi...,90,False,True,True,3,3.0,6.0
5103,51303748,https://www.airbnb.com/users/show/51303748,Eren,"Kadikoy, Çanakkale, Turkey",NaN,https://a0.muscache.com/im/pictures/89a1b839-2...,https://a0.muscache.com/im/pictures/89a1b839-2...,0,False,True,False,2,2.0,2.0

In [119]:
df_2  #amenities

      amenities_length
0                   11
1                   23
2                   11
3                   16
4                   13
...                ...
5550                21
5551                32
5552                 9
5553                15
5554                15

[5555 rows x 1 columns]

In [120]:
df_3  #availability

      availability_30  availability_60  availability_90  availability_365
0                   0                0                0                93
1                  30               31               31               243
2                  10               10               21               296
3                  28               58               88               363
4                   0                0                0                32
...               ...              ...              ...               ...
5548                0               15               28               212
5549                0                0                0               139
5550               17               35               63               322
5551                2               11               15               154
5553               28               54               82               351

[2871 rows x 4 columns]

In [121]:
df_4  #reviews

,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,review_scores_rating
0,10,9,10,10,10,10,94
1,9,10,10,8,9,9,88
2,10,6,8,8,8,8,80
3,0,0,0,0,0,0,0
5,10,10,10,10,10,8,100
...,...,...,...,...,...,...,...
5521,10,4,8,6,10,10,60
5526,10,10,10,8,10,10,80
5529,9,8,9,9,8,9,79
5538,10,10,8,8,8,10,80
5545,8,9,10,10,8,7,80

In [122]:
airbnb_1

,name,property_type,room_type,bed_type,minimum_nights,maximum_nights,cancellation_policy,accommodates,bedrooms,beds,number_of_reviews,bathrooms,price,extra_people,guests_included
0,New York City - Upper West Side Apt,Apartment,Private room,Real Bed,6.0,360,strict_14_with_grace_period,2.0,1,1.0,70,1.0,135.0,0,1
1,Deluxe Loft Suite,Apartment,Entire home/apt,Real Bed,3.0,1125,strict_14_with_grace_period,3.5,0,2.0,5,1.0,205.0,0,1
2,Catete's Colonial Big Hause Room B,House,Private room,Real Bed,2.0,1125,strict_14_with_grace_period,3.5,1,6.0,1,1.0,250.0,40,4
3,Apt Linda Vista Lagoa - Rio,Apartment,Private room,Real Bed,1.0,1125,flexible,2.0,1,1.0,0,1.0,701.0,0,1
4,Ligne verte - à 15 min de métro du centre ville.,Apartment,Entire home/apt,Real Bed,2.0,1125,moderate,2.0,0,1.0,0,1.0,43.0,12,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5550,Lindo apto quarto e sala ao lado do mar de Copa!,Apartment,Entire home/apt,Real Bed,2.0,1125,strict_14_with_grace_period,3.5,1,2.0,19,1.0,119.0,0,1
5551,Beautiful Place in the Middle of Manhattan,Apartment,Entire home/apt,Real Bed,1.0,1125,strict_14_with_grace_period,2.0,1,1.0,180,1.0,160.0,20,2
5552,Large double room in Bondi,Apartment,Private room,Real Bed,3.0,1125,moderate,2.0,1,1.0,0,1.0,60.0,50,2
5553,StayIN Oporto Música - Apartment,Apartment,Entire home/apt,Real Bed,1.0,1125,strict_14_with_grace_period,3.5,8,6.0,20,1.0,500.0,30,16
5554,Kadıköy-Altıyol,House,Entire home/apt,Real Bed,1.0,1125,flexible,2.0,2,3.0,0,1.0,501.0,0,1

In [123]:
import seaborn as sns
tc=airbnb_1.groupby(['property_type'])['price'].sum().sort_values(ascending=False).nlargest(10).to_frame()

In [124]:
tc=tc.reset_index()
tc

        property_type     price
0           Apartment  925800.0
1               House  202404.0
2         Condominium  136810.0
3  Serviced apartment   80773.0
4   Bed and breakfast   33187.0
5                Loft   27784.0
6               Hotel   20576.0
7           Townhouse   19764.0
8      Boutique hotel   16192.0
9               Villa   15358.0

In [125]:
airbnb_data10=pd.concat([airbnb_1,df,df_1,df_2,df_3,df_4],axis=1)

In [126]:
airbnb_data10

,name,property_type,room_type,bed_type,minimum_nights,maximum_nights,cancellation_policy,accommodates,bedrooms,beds,number_of_reviews,bathrooms,price,extra_people,guests_included,street,suburb,government_area,market,country,country_code,type,Latitude,Longitude,is_location_exact,host_id,host_url,host_name,host_location,host_about,host_thumbnail_urlt,host_picture_url,host_response_rate,host_is_superhost,host_has_profile_pic,host_identity_verified,host_listings_count,host_total_listings_count,host_verifications,amenities_length,availability_30,availability_60,availability_90,availability_365,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,review_scores_rating
0,New York City - Upper West Side Apt,Apartment,Private room,Real Bed,6.0,360.0,strict_14_with_grace_period,2.0,1.0,1.0,70.0,1.0,135.0,0.0,1.0,New York,Manhattan,Upper West Side,New York,United States,US,Point,40.799620,-73.965230,False,454250.0,https://www.airbnb.com/users/show/454250,Greta,"New York, New York, United States",By now I have lived longer in the city than th...,https://a0.muscache.com/im/pictures/f1022be4-e...,https://a0.muscache.com/im/pictures/f1022be4-e...,100.0,True,True,True,3.0,3.0,6.0,11,0.0,0.0,0.0,93.0,10.0,9.0,10.0,10.0,10.0,10.0,94.0
1,Deluxe Loft Suite,Apartment,Entire home/apt,Real Bed,3.0,1125.0,strict_14_with_grace_period,3.5,0.0,2.0,5.0,1.0,205.0,0.0,1.0,Brooklyn,Greenpoint,Greenpoint,New York,United States,US,Point,40.727780,-73.944720,True,47554473.0,https://www.airbnb.com/users/show/47554473,Mae,US,NaN,https://a0.muscache.com/im/pictures/c680ce22-d...,https://a0.muscache.com/im/pictures/c680ce22-d...,100.0,False,True,False,13.0,8.5,6.0,23,30.0,31.0,31.0,243.0,9.0,10.0,10.0,8.0,9.0,9.0,88.0
2,Catete's Colonial Big Hause Room B,House,Private room,Real Bed,2.0,1125.0,strict_14_with_grace_period,3.5,1.0,6.0,1.0,1.0,250.0,40.0,4.0,Rio de Janeiro,Catete,Catete,Rio De Janeiro,Brazil,BR,Point,-22.926382,-43.180157,True,51326285.0,https://www.airbnb.com/users/show/51326285,Beatriz,"Rio de Janeiro, State of Rio de Janeiro, Brazil",NaN,https://a0.muscache.com/im/pictures/eb09c9cb-b...,https://a0.muscache.com/im/pictures/eb09c9cb-b...,80.0,False,True,True,5.0,5.0,6.0,11,10.0,10.0,21.0,296.0,10.0,6.0,8.0,8.0,8.0,8.0,80.0
3,Apt Linda Vista Lagoa - Rio,Apartment,Private room,Real Bed,1.0,1125.0,flexible,2.0,1.0,1.0,0.0,1.0,701.0,0.0,1.0,Rio de Janeiro,Lagoa,Lagoa,Rio De Janeiro,Brazil,BR,Point,-22.971951,-43.205047,True,51496939.0,https://www.airbnb.com/users/show/51496939,Livia,BR,NaN,https://a0.muscache.com/im/pictures/b7911710-9...,https://a0.muscache.com/im/pictures/b7911710-9...,0.0,False,True,False,1.0,1.0,4.0,16,28.0,58.0,88.0,363.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Ligne verte - à 15 min de métro du centre ville.,Apartment,Entire home/apt,Real Bed,2.0,1125.0,moderate,2.0,0.0,1.0,0.0,1.0,43.0,12.0,1.0,Montréal,Hochelaga-Maisonneuve,Mercier-Hochelaga-Maisonneuve,Montreal,Canada,CA,Point,45.545480,-73.549490,False,7140229.0,https://www.airbnb.com/users/show/7140229,Caro,"Montreal, Quebec, Canada",NaN,https://a0.muscache.com/im/pictures/user/c6477...,https://a0.muscache.com/im/pictures/user/c6477...,100.0,False,True,False,1.0,1.0,5.0,13,0.0,0.0,0.0,32.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5551,Beautiful Place in the Middle of Manhattan,Apartment,Entire home/apt,Real Bed,1.0,1125.0,strict_14_with_grace_period,2.0,1.0,1.0,180.0,1.0,160.0,20.0,2.0,New York,Manhattan,Upper East Side,New York,United States,US,Point,40.762660,-73.962050,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32,2.0,11.0,15.0,154.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5552,Large double room in Bondi,Apartment,Private room,Real Bed,3.0,1125.0,moderate,2.0,1.0,1.0,0.0,1.0,60.0,50.0,2.0,Bondi Beach,Bondi,Waverley,Sydney,Australia,AU,Point,-33.892980,151.265420,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5553,StayIN Oporto Música - Apartment,Apartment,Entire home/apt,Real Bed,1.0,1125.0,strict_14_with_grace_period,3.5,8.0,6.0,20.0,1.0,500.0,30.0,16.0,Porto,Porto,Cedofeita,Porto,Portugal,PT,Point,41.151270,-8.606220,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,28.0,54.0,82.0,351.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5554,Kadıköy-Altıyol,House,Entire home/apt,Real Bed,1.0,1125.0,flexible,2.0,2.0,3.0,0.0,1.0,501.0,0.0,1.0,Kadıköy,Moda,Kadikoy,Istanbul,Turkey,TR,Point,40.985630,29.030790,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4296,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Honolulu,Honolulu,Primary Urban Center,Oahu,United States,US,Point,21.285550,-157.839230,False,5829222.0,https://www.airbnb.com/users/show/5829222,Muge,Istanbul,I am a travel addict! I travelled all around t...,https://a0.muscache.com/im/users/5829222/profi...,https://a0.muscache.com/im/users/5829222/profi...,92.0,False,True,True,8.0,8.0,6.0,13,0.0,5.0,35.0,190.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [127]:
airbnb_data10.isnull().sum()

name                              1
property_type                     1
room_type                         1
bed_type                          1
minimum_nights                    1
maximum_nights                    1
cancellation_policy               1
accommodates                      1
bedrooms                          1
beds                              1
number_of_reviews                 1
bathrooms                         1
price                             1
extra_people                      1
guests_included                   1
street                            0
suburb                            0
government_area                   0
market                            0
country                           0
country_code                      0
type                              0
Latitude                          0
Longitude                         0
is_location_exact                 0
host_id                         459
host_url                        459
host_name                       459
host_location                   459
host_about                     2590
host_thumbnail_urlt             459
host_picture_url                459
host_response_rate              459
host_is_superhost               459
host_has_profile_pic            459
host_identity_verified          459
host_listings_count             459
host_total_listings_count       459
host_verifications              459
amenities_length                  0
availability_30                2684
availability_60                2684
availability_90                2684
availability_365               2684
review_scores_accuracy         4391
review_scores_cleanliness      4391
review_scores_checkin          4391
review_scores_communication    4391
review_scores_location         4391
review_scores_value            4391
review_scores_rating           4391
dtype: int64

In [128]:
airbnb_data10['host_location'].fillna(airbnb_data10['host_location'].mode(), inplace=True)

In [129]:
airbnb_data10['name'].fillna(airbnb_data10['name'].mode(), inplace=True)

In [130]:
airbnb_data10=airbnb_data10.drop(columns=['host_id','host_is_superhost','host_has_profile_pic','host_identity_verified'],axis=1)

In [131]:
airbnb_data10['host_response_rate'].fillna(airbnb_data10['host_response_rate'].mean(), inplace=True)
#'host_listings_count','host_total_listings_count','host_verifications'

In [132]:
airbnb_data10['host_listings_count'].fillna(airbnb_data10['host_listings_count'].mean(), inplace=True)
airbnb_data10['host_total_listings_count'].fillna(airbnb_data10['host_total_listings_count'].mean(), inplace=True)
airbnb_data10['host_verifications'].fillna(airbnb_data10['host_verifications'].mean(), inplace=True)

In [133]:
airbnb_data10.dropna(subset=['host_name','host_location'],inplace=True)
airbnb_data10.dropna(subset=['name'],inplace=True)

In [134]:
airbnb_data10['availability_365'].fillna(airbnb_data10['availability_365'].mean(), inplace=True)

In [135]:
airbnb_data10=airbnb_data10.drop(columns=['review_scores_accuracy','review_scores_cleanliness','review_scores_checkin','review_scores_communication','review_scores_location','review_scores_value'],axis=1)

In [136]:
airbnb_data10['review_scores_rating'].fillna(airbnb_data10['review_scores_rating'].mean(), inplace=True)

In [137]:
airbnb_data10['availability_30'].fillna(airbnb_data10['availability_30'].mean(), inplace=True)
airbnb_data10['availability_60'].fillna(airbnb_data10['availability_60'].mean(), inplace=True)
airbnb_data10['availability_90'].fillna(airbnb_data10['availability_90'].mean(), inplace=True)

In [138]:
airbnb_data10.isnull().sum()

name                            0
property_type                   0
room_type                       0
bed_type                        0
minimum_nights                  0
maximum_nights                  0
cancellation_policy             0
accommodates                    0
bedrooms                        0
beds                            0
number_of_reviews               0
bathrooms                       0
price                           0
extra_people                    0
guests_included                 0
street                          0
suburb                          0
government_area                 0
market                          0
country                         0
country_code                    0
type                            0
Latitude                        0
Longitude                       0
is_location_exact               0
host_url                        0
host_name                       0
host_location                   0
host_about                   2131
host_thumbnail_urlt             0
host_picture_url                0
host_response_rate              0
host_listings_count             0
host_total_listings_count       0
host_verifications              0
amenities_length                0
availability_30                 0
availability_60                 0
availability_90                 0
availability_365                0
review_scores_rating            0
dtype: int64

In [139]:
airbnb_data1=airbnb_data10
airbnb_data1 #/content/sample_data

,name,property_type,room_type,bed_type,minimum_nights,maximum_nights,cancellation_policy,accommodates,bedrooms,beds,number_of_reviews,bathrooms,price,extra_people,guests_included,street,suburb,government_area,market,country,country_code,type,Latitude,Longitude,is_location_exact,host_url,host_name,host_location,host_about,host_thumbnail_urlt,host_picture_url,host_response_rate,host_listings_count,host_total_listings_count,host_verifications,amenities_length,availability_30,availability_60,availability_90,availability_365,review_scores_rating
0,New York City - Upper West Side Apt,Apartment,Private room,Real Bed,6.0,360.0,strict_14_with_grace_period,2.0,1.0,1.0,70.0,1.0,135.0,0.0,1.0,New York,Manhattan,Upper West Side,New York,United States,US,Point,40.799620,-73.965230,False,https://www.airbnb.com/users/show/454250,Greta,"New York, New York, United States",By now I have lived longer in the city than th...,https://a0.muscache.com/im/pictures/f1022be4-e...,https://a0.muscache.com/im/pictures/f1022be4-e...,100.0,3.0,3.0,6.0,11,0.000000,0.000000,0.000000,93.000000,94.000000
1,Deluxe Loft Suite,Apartment,Entire home/apt,Real Bed,3.0,1125.0,strict_14_with_grace_period,3.5,0.0,2.0,5.0,1.0,205.0,0.0,1.0,Brooklyn,Greenpoint,Greenpoint,New York,United States,US,Point,40.727780,-73.944720,True,https://www.airbnb.com/users/show/47554473,Mae,US,NaN,https://a0.muscache.com/im/pictures/c680ce22-d...,https://a0.muscache.com/im/pictures/c680ce22-d...,100.0,13.0,8.5,6.0,23,30.000000,31.000000,31.000000,243.000000,88.000000
2,Catete's Colonial Big Hause Room B,House,Private room,Real Bed,2.0,1125.0,strict_14_with_grace_period,3.5,1.0,6.0,1.0,1.0,250.0,40.0,4.0,Rio de Janeiro,Catete,Catete,Rio De Janeiro,Brazil,BR,Point,-22.926382,-43.180157,True,https://www.airbnb.com/users/show/51326285,Beatriz,"Rio de Janeiro, State of Rio de Janeiro, Brazil",NaN,https://a0.muscache.com/im/pictures/eb09c9cb-b...,https://a0.muscache.com/im/pictures/eb09c9cb-b...,80.0,5.0,5.0,6.0,11,10.000000,10.000000,21.000000,296.000000,80.000000
3,Apt Linda Vista Lagoa - Rio,Apartment,Private room,Real Bed,1.0,1125.0,flexible,2.0,1.0,1.0,0.0,1.0,701.0,0.0,1.0,Rio de Janeiro,Lagoa,Lagoa,Rio De Janeiro,Brazil,BR,Point,-22.971951,-43.205047,True,https://www.airbnb.com/users/show/51496939,Livia,BR,NaN,https://a0.muscache.com/im/pictures/b7911710-9...,https://a0.muscache.com/im/pictures/b7911710-9...,0.0,1.0,1.0,4.0,16,28.000000,58.000000,88.000000,363.000000,0.000000
4,Ligne verte - à 15 min de métro du centre ville.,Apartment,Entire home/apt,Real Bed,2.0,1125.0,moderate,2.0,0.0,1.0,0.0,1.0,43.0,12.0,1.0,Montréal,Hochelaga-Maisonneuve,Mercier-Hochelaga-Maisonneuve,Montreal,Canada,CA,Point,45.545480,-73.549490,False,https://www.airbnb.com/users/show/7140229,Caro,"Montreal, Quebec, Canada",NaN,https://a0.muscache.com/im/pictures/user/c6477...,https://a0.muscache.com/im/pictures/user/c6477...,100.0,1.0,1.0,5.0,13,0.000000,0.000000,0.000000,32.000000,86.048051
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5099,OPO.APT - Art Déco Apartment 110-1,Apartment,Entire home/apt,Real Bed,3.0,1125.0,strict_14_with_grace_period,3.5,2.0,4.0,127.0,1.0,59.0,4.0,4.0,Porto,Porto,Cedofeita,Porto,Portugal,PT,Point,41.155040,-8.623050,True,https://www.airbnb.com/users/show/1403065,Clarissa,"Rio de Janeiro, Rio de Janeiro, Brazil","I am Brazilian, 39 y.o. live in Rio de Janeiro...",https://a0.muscache.com/im/pictures/8bd5fd4e-3...,https://a0.muscache.com/im/pictures/8bd5fd4e-3...,100.0,2.0,2.0,4.0,20,10.000000,16.000000,24.000000,223.000000,86.048051
5100,3 bedroom + 2 bathroom apt near MTR,Condominium,Entire home/apt,Real Bed,1.0,1125.0,strict_14_with_grace_period,3.5,3.0,4.0,106.0,1.0,1052.0,100.0,6.0,Hong Kong,Yau Tsim Mong,Yau Tsim Mong,Hong Kong,Hong Kong,HK,Point,22.307200,114.165320,True,https://www.airbnb.com/users/show/40540485,Miguel,"New York, New York, United States",We are a married couple who loves to travel ev...,https://a0.muscache.com/im/pictures/f2065606-7...,https://a0.muscache.com/im/pictures/f2065606-7...,100.0,1.0,1.0,5.0,12,11.000000,17.000000,33.000000,290.000000,78.000000
5101,"[4] New BedRm by C.Park and 1,B,C",Apartment,Private room,Real Bed,1.0,1125.0,strict_14_with_grace_period,2.0,1.0,1.0,175.0,1.0,95.0,0.0,1.0,New York,Upper West Side,Upper West Side,New York,United States,US,Point,40.798550,-73.963890,True,https://www.airbnb.com/users/show/47615848,Lucy,"Bondi Beach, New South Wales, Australia",NaN,https://a0.muscache.com/im/pictures/b4675d0a-f...,https://a0.muscache.com/im/pictures/b4675d0a-f...,0.0,1.0,1.0,2.0,22,12.000000,36.000000,60.000000,149.000000,86.048051
5102,Double bed room for 2 travellers,Apartment,Private room,Real Bed,6.0,365.0,moderate,2.0,1.0,1.0,15.0,1.0,377.0,100.0,2.0,Mong Kok,Mong Kok,Yau Tsim Mong,Hong Kong,Hong Kong,HK,Point,22.318270,114.168530,True,https://www.airbnb.com/users/show/2296185,Manuel,"Jovim, Porto, Portugal",From Porto,https://a0.muscache.com/im/users/2296185/profi...,https://a0.muscache.com/im/users/2296185/profi...,90.0,3.0,3.0,6.0,6,0.000000,12.000000,42.000000,317.000000,86.048051
5103,Long Island City- Furnished Studio,Apartment,Entire home/apt,Real Bed,1.0,1125.0,flexible,2.0,0.0,1.0,9.0,1.0,110.0,25.0,2.0,Queens,Queens,Long Island City,New York,United States,US,Point,40.752260,-73.940890,True,https://www.airbnb.com/users/show/51303748,Eren,"Kadikoy, Çanakkale, Turkey",NaN,https://a0.muscache.com/im/pictures/89a1b839-2...,https://a0.muscache.com/im/pictures/89a1b839-2...,0.0,2.0,2.0,2.0,12,11.105461,26.381544,44.543126,198.057627,86.048051

In [140]:
airbnb_data = pd.DataFrame(airbnb_data1)

In [141]:
airbnb_data.to_csv('airbnb_data.csv', index=False)

In [142]:
airbnb_data.duplicated().sum()

0